import type { Locale } from "./i18n";

/**
 * Testi dei fumetti dei Creator (pacchetto FUMETTI, 29/09/2026): voci fra le news, pagina del fumetto, elenco
 * /news/comics, modulo di pubblicazione, errori, "I miei fumetti" in /account, comandi del proprietario e dello staff,
 * paragrafo della privacy. Un modulo solo nelle tre lingue, come communityGuideLabels.ts; `en` è il tipo di riferimento.
 * Segnaposto fra graffe ({name}, {date}, {n}, {total}, {max}, {min}, {minw}…): li riempie `fillLabel` (deckQuality.ts).
 * Nessun import a runtime: comics.test.ts lo carica con `node --test` e controlla chiavi e segnaposto.
 * Spagnolo neutro con il tú (docs/spagnolo.md): "cómic" e "página", mai parole che cambiano da paese a paese.
 */
const en = {
  /** pastiglia accanto alla data nelle news e post-it della home */
  pill: "Comic",
  by: "Comic by {name}",
  read: "Read the comic",
  page: {
    /** in coda al titolo per la SERP ("{title} · Origins TCG comic") */
    metaSuffix: "Origins TCG comic",
    published: "Published on {date}",
    updated: "updated on {date}",
    pagesOne: "1 page",
    pagesMany: "{n} pages",
    pageAlt: "Page {n} of {total}",
    pageAltText: "Page {n} of {total}. {text}",
    open: "Open page {n} full size",
    transcript: "Transcript",
    transcriptIntro: "The text of every page, in order: for screen readers and for anyone who prefers to read it.",
    noText: "No text on this page.",
    translatedNote: "Texts translated automatically from {lang}: the balloons stay in the original language.",
    originalNote: "The texts are in {lang}: the translation will be ready in a few minutes.",
    moreTitle: "More comics",
    allComics: "All the comics",
    allNews: "All the news",
    unavailable: "Comics are not available yet: try again in a few minutes.",
  },
  hub: {
    title: "Origins TCG comics",
    metaTitle: "Origins TCG comics by the community creators",
    description: "Comics about Origins TCG drawn by the creators of the OriginsMeta community: news, stories and life in the game, with the texts in English, Italian and Spanish.",
    intro: "Comics about Origins TCG drawn by the creators of the community: news, stories and life in the game. They also come out among the news.",
    empty: "No comics yet: the first one is on its way.",
  },
  /** riquadro in /news per chi può pubblicare (Creator e Staff), deciso nel browser */
  cta: {
    title: "Publish a comic",
    text: "As a Creator you can publish your comics among the news: pages, cover and texts, translated by the site into the other two languages.",
    button: "Publish a comic",
  },
  newTitle: "Publish a comic",
  newDescription: "Publish an Origins TCG comic on OriginsMeta: pages, cover and texts, among the news, under your name and translated automatically.",
  newIntro: "Pages, cover and texts: the comic comes out among the news, under your name, with its own page. The site translates the title, the presentation and the texts of the pages into the other two languages.",
  editTitle: "Edit the comic",
  notAllowed: {
    title: "Comics are for Creators and Staff",
    text: "Publishing comics among the news is for the Creator and Staff roles. If you draw comics about Origins TCG, write to the staff from your messages.",
  },
  editor: {
    lang: "Language of the texts",
    langHint: "The language of the balloons and of the texts below. The site translates the title, the presentation and the page texts into the other two languages.",
    title: "Title",
    summary: "Presentation",
    summaryHint: "2 or 3 sentences, from {min} to {max} characters: they appear in the news list, on the home page and when the link is shared.",
    cover: "Cover",
    coverHint: "16:9, at least {minw} × {minh} px ({w} × {h} is ideal), PNG, JPG or WebP: we crop it to 16:9 from the center. It appears in the news list, on the home page and when the link is shared.",
    coverUpload: "Upload the cover",
    coverReplace: "Change the cover",
    coverAlt: "Cover of the comic",
    uploading: "Uploading…",
    pages: "Pages",
    pagesHint: "Vertical images read from top to bottom: {w} px wide and up to {h} px tall (9:16). A longer story goes in more images, up to {max}; single panels of 1080 × 1350 (4:5) are fine too. PNG, JPG or WebP up to 20 MB: the site shrinks and converts them.",
    pagesAdd: "Add pages",
    pagesUploading: "Uploading page {n} of {total}…",
    pagesCount: "{n} of {max} pages",
    pageLabel: "Page {n}",
    pageText: "Text of page {n}",
    pageTextHint: "Dialogues, captions and sound effects, in reading order. Optional, but screen readers and Google read this, and it's what we translate.",
    pageUp: "Move up",
    pageDown: "Move down",
    pageRemove: "Remove",
    uploadErrors: {
      type: "This file is not a PNG, JPG or WebP image.",
      tooBig: "The image is too heavy even after compression: try a lighter one.",
      upload: "The upload didn't go through: check your connection and try again.",
      limit: "You have reached the limit of uploaded images: delete a comic you no longer need, or write to the staff.",
      source: "This file is over 20 MB: export a lighter version.",
      full: "A comic has at most {max} pages.",
    },
    rights: "Only drawings that are yours or that you have the right to publish, and no cards that haven't been announced yet.",
    saveDraft: "Save draft",
    publish: "Publish",
    update: "Save changes",
    unpublish: "Move back to drafts",
    saving: "Saving…",
    saved: "Draft saved.",
    statusDraft: "Draft: only you can see it.",
    statusPublished: "Published: every change goes online right away.",
    statusHidden: "Hidden by the staff: write to the staff from your messages to know why.",
    counter: "{n}/{max}",
    consent: "Publishing puts the comic online among the news, under your name, with the site's automatic translations of the texts, and announces it on our Discord. You can move it back to drafts or delete it whenever you want.",
  },
  errors: {
    lang: "Choose the language of the texts.",
    title: "Title: from {min} to {max} characters on one line (a draft needs just one).",
    summary: "Presentation: from {min} to {max} characters to publish (a draft can leave it empty).",
    pages: "Pages: from 1 to {max} to publish.",
    page: "Page {n}: the image or its text can't be used. Upload it again.",
    cover: "Upload a cover to publish.",
    notLoggedIn: "Sign in to publish a comic.",
    forbidden: "Publishing comics is for Creators and Staff.",
    disabled: "Accounts are switched off on this copy of the site.",
    unavailable: "Comics are not available yet: try again in a few minutes.",
    comic_daily_limit: "You have already published 3 new comics in the last 24 hours: save this one as a draft and publish it tomorrow.",
    comic_limit: "You have reached 500 comics: delete an old one to publish a new one.",
    comic_rate: "You have started 10 comics in the last 24 hours: try again tomorrow.",
    comic_hidden: "The staff has hidden this comic: write to the staff from your messages.",
    comic_hidden_recent: "The staff hid one of your comics in the last 24 hours: you can publish again tomorrow. Save this one as a draft meanwhile.",
    comic_status: "This change is for the staff only.",
    comic_file: "One of the images can't be found: upload it again.",
    comic_translation: "The translation couldn't be saved: the texts stay as they are.",
    comic_reserved_fields: "This change is not allowed.",
    duplicate: "Something went wrong with the address of the comic: try again.",
    db: "Saving failed: try again in a moment.",
    /** {n} = secondi da aspettare */
    tooFast: "Wait {n} seconds before saving again.",
  },
  account: {
    title: "My comics",
    intro: "Drafts, published comics and comics hidden by the staff. Only the published ones appear on the site, among the news.",
    none: "No comics yet.",
    write: "Publish a comic",
    view: "View",
    edit: "Edit",
    status: { draft: "Draft", published: "Published", hidden: "Hidden by the staff" },
  },
  owner: {
    edit: "Edit",
    unpublish: "Move back to drafts",
    delete: "Delete",
    confirmDelete: "Delete this comic and its images? This can't be undone.",
    hide: "Hide (staff)",
    unhide: "Put back online (staff)",
  },
  profile: {
    title: "Comics",
  },
  /** paragrafo della privacy (#community-comics) */
  privacy:
    "Comics. Creators and Staff can publish comics among the news. The pages and the cover are stored like the other images you upload on the site (see above: your browser shrinks and re-encodes them, removing data such as the location); the title, the presentation and the texts of the pages are public on the comic's page, with your name and a link to your profile, and the site translates the title, the presentation and the texts into the other two languages with the same service used for the guides. When a comic comes out, whoever follows you receives a notice and our Discord announces it. You can edit a comic, move it back to drafts or delete it at any time: deleting it deletes its images too. The staff can hide a comic that breaks the site rules.",
};

export type ComicLabels = typeof en;

const it: ComicLabels = {
  pill: "Fumetto",
  by: "Fumetto di {name}",
  read: "Leggi il fumetto",
  page: {
    metaSuffix: "fumetto di Origins TCG",
    published: "Pubblicato il {date}",
    updated: "aggiornato il {date}",
    pagesOne: "1 tavola",
    pagesMany: "{n} tavole",
    pageAlt: "Tavola {n} di {total}",
    pageAltText: "Tavola {n} di {total}. {text}",
    open: "Apri la tavola {n} a grandezza piena",
    transcript: "Trascrizione",
    transcriptIntro: "Il testo di ogni tavola, in ordine: per chi usa un lettore di schermo e per chi preferisce leggerlo.",
    noText: "Nessun testo in questa tavola.",
    translatedNote: "Testi tradotti in automatico (l'originale è in {lang}): i balloon restano nella lingua originale.",
    originalNote: "I testi sono in {lang}: la traduzione arriva fra qualche minuto.",
    moreTitle: "Altri fumetti",
    allComics: "Tutti i fumetti",
    allNews: "Tutte le news",
    unavailable: "I fumetti non sono ancora disponibili: riprova fra qualche minuto.",
  },
  hub: {
    title: "Fumetti di Origins TCG",
    metaTitle: "Fumetti di Origins TCG dei creator della community",
    description: "Fumetti su Origins TCG disegnati dai creator della community di OriginsMeta: notizie, storie e vita di gioco, con i testi in italiano, inglese e spagnolo.",
    intro: "Fumetti su Origins TCG disegnati dai creator della community: notizie, storie e vita di gioco. Escono anche fra le news.",
    empty: "Ancora nessun fumetto: il primo sta arrivando.",
  },
  cta: {
    title: "Pubblica un fumetto",
    text: "Come Creator puoi pubblicare i tuoi fumetti fra le news: tavole, copertina e testi, tradotti dal sito nelle altre due lingue.",
    button: "Pubblica un fumetto",
  },
  newTitle: "Pubblica un fumetto",
  newDescription: "Pubblica un fumetto su Origins TCG su OriginsMeta: tavole, copertina e testi, fra le news, con il tuo nome e tradotto in automatico.",
  newIntro: "Tavole, copertina e testi: il fumetto esce fra le news, con il tuo nome e una pagina sua. Il sito traduce titolo, presentazione e testi delle tavole nelle altre due lingue.",
  editTitle: "Modifica il fumetto",
  notAllowed: {
    title: "I fumetti sono per i Creator e lo Staff",
    text: "Pubblicare fumetti fra le news è per i ruoli Creator e Staff. Se disegni fumetti su Origins TCG, scrivi allo staff dai tuoi messaggi.",
  },
  editor: {
    lang: "Lingua dei testi",
    langHint: "La lingua dei balloon e dei testi qui sotto. Il sito traduce titolo, presentazione e testi delle tavole nelle altre due lingue.",
    title: "Titolo",
    summary: "Presentazione",
    summaryHint: "2 o 3 frasi, da {min} a {max} caratteri: compaiono nell'elenco delle news, in home e quando si condivide il link.",
    cover: "Copertina",
    coverHint: "16:9, almeno {minw} × {minh} px (l'ideale è {w} × {h}), PNG, JPG o WebP: la ritagliamo al centro in 16:9. Compare nell'elenco delle news, in home e quando si condivide il link.",
    coverUpload: "Carica la copertina",
    coverReplace: "Cambia la copertina",
    coverAlt: "Copertina del fumetto",
    uploading: "Caricamento…",
    pages: "Tavole",
    pagesHint: "Immagini verticali da leggere dall'alto in basso: larghe {w} px e alte fino a {h} px (9:16). Una storia più lunga va in più immagini, fino a {max}; vanno bene anche vignette singole da 1080 × 1350 (4:5). PNG, JPG o WebP fino a 20 MB: il sito le riduce e le converte.",
    pagesAdd: "Aggiungi tavole",
    pagesUploading: "Caricamento della tavola {n} di {total}…",
    pagesCount: "{n} di {max} tavole",
    pageLabel: "Tavola {n}",
    pageText: "Testo della tavola {n}",
    pageTextHint: "Dialoghi, didascalie ed effetti sonori, nell'ordine di lettura. Facoltativo, ma è quello che leggono i lettori di schermo e Google, ed è quello che traduciamo.",
    pageUp: "Sposta su",
    pageDown: "Sposta giù",
    pageRemove: "Togli",
    uploadErrors: {
      type: "Questo file non è un'immagine PNG, JPG o WebP.",
      tooBig: "L'immagine è troppo pesante anche dopo la compressione: provane una più leggera.",
      upload: "Il caricamento non è andato a buon fine: controlla la connessione e riprova.",
      limit: "Hai raggiunto il limite di immagini caricate: elimina un fumetto che non ti serve più, o scrivi allo staff.",
      source: "Questo file supera i 20 MB: esportane una versione più leggera.",
      full: "Un fumetto ha al massimo {max} tavole.",
    },
    rights: "Solo disegni tuoi o che hai il diritto di pubblicare, e niente carte non ancora annunciate.",
    saveDraft: "Salva bozza",
    publish: "Pubblica",
    update: "Salva le modifiche",
    unpublish: "Riporta tra le bozze",
    saving: "Salvataggio…",
    saved: "Bozza salvata.",
    statusDraft: "Bozza: la vedi solo tu.",
    statusPublished: "Pubblicato: ogni modifica va subito online.",
    statusHidden: "Nascosto dallo staff: scrivi allo staff dai tuoi messaggi per sapere perché.",
    counter: "{n}/{max}",
    consent: "Pubblicando, il fumetto va online fra le news con il tuo nome, con le traduzioni automatiche dei testi fatte dal sito, e lo annunciamo sul nostro Discord. Puoi riportarlo tra le bozze o eliminarlo quando vuoi.",
  },
  errors: {
    lang: "Scegli la lingua dei testi.",
    title: "Titolo: da {min} a {max} caratteri su una riga (a una bozza ne basta uno).",
    summary: "Presentazione: da {min} a {max} caratteri per pubblicare (una bozza può lasciarla vuota).",
    pages: "Tavole: da 1 a {max} per pubblicare.",
    page: "Tavola {n}: l'immagine o il suo testo non vanno bene. Caricala di nuovo.",
    cover: "Carica una copertina per pubblicare.",
    notLoggedIn: "Accedi per pubblicare un fumetto.",
    forbidden: "Pubblicare fumetti è per i Creator e lo Staff.",
    disabled: "Gli account sono spenti in questa copia del sito.",
    unavailable: "I fumetti non sono ancora disponibili: riprova fra qualche minuto.",
    comic_daily_limit: "Hai già pubblicato 3 fumetti nuovi nelle ultime 24 ore: salva questo come bozza e pubblicalo domani.",
    comic_limit: "Hai raggiunto 500 fumetti: eliminane uno vecchio per pubblicarne uno nuovo.",
    comic_rate: "Hai iniziato 10 fumetti nelle ultime 24 ore: riprova domani.",
    comic_hidden: "Lo staff ha nascosto questo fumetto: scrivi allo staff dai tuoi messaggi.",
    comic_hidden_recent: "Lo staff ha nascosto un tuo fumetto nelle ultime 24 ore: potrai pubblicare di nuovo domani. Intanto salva questo come bozza.",
    comic_status: "Questa modifica è riservata allo staff.",
    comic_file: "Una delle immagini non si trova: caricala di nuovo.",
    comic_translation: "Non è stato possibile salvare la traduzione: i testi restano come sono.",
    comic_reserved_fields: "Questa modifica non è consentita.",
    duplicate: "Qualcosa è andato storto con l'indirizzo del fumetto: riprova.",
    db: "Salvataggio non riuscito: riprova fra un momento.",
    tooFast: "Aspetta {n} secondi prima di salvare di nuovo.",
  },
  account: {
    title: "I miei fumetti",
    intro: "Bozze, fumetti pubblicati e fumetti nascosti dallo staff. Sul sito, fra le news, compaiono solo i pubblicati.",
    none: "Ancora nessun fumetto.",
    write: "Pubblica un fumetto",
    view: "Apri",
    edit: "Modifica",
    status: { draft: "Bozza", published: "Pubblicato", hidden: "Nascosto dallo staff" },
  },
  owner: {
    edit: "Modifica",
    unpublish: "Riporta tra le bozze",
    delete: "Elimina",
    confirmDelete: "Eliminare questo fumetto e le sue immagini? Non si può annullare.",
    hide: "Nascondi (staff)",
    unhide: "Rimetti online (staff)",
  },
  profile: {
    title: "Fumetti",
  },
  privacy:
    "Fumetti. I Creator e lo Staff possono pubblicare fumetti fra le news. Tavole e copertina si salvano come le altre immagini che carichi sul sito (vedi sopra: il tuo browser le riduce e le ricodifica, togliendo dati come la posizione); titolo, presentazione e testi delle tavole sono pubblici nella pagina del fumetto, con il tuo nome e il link al tuo profilo, e il sito traduce titolo, presentazione e testi nelle altre due lingue con lo stesso servizio usato per le guide. Quando esce un fumetto, chi ti segue riceve un avviso e il nostro Discord lo annuncia. Puoi modificare un fumetto, riportarlo tra le bozze o eliminarlo quando vuoi: eliminandolo si cancellano anche le sue immagini. Lo staff può nascondere un fumetto che non rispetta le regole del sito.",
};

const es: ComicLabels = {
  pill: "Cómic",
  by: "Cómic de {name}",
  read: "Lee el cómic",
  page: {
    metaSuffix: "cómic de Origins TCG",
    published: "Publicado el {date}",
    updated: "actualizado el {date}",
    pagesOne: "1 página",
    pagesMany: "{n} páginas",
    pageAlt: "Página {n} de {total}",
    pageAltText: "Página {n} de {total}. {text}",
    open: "Abrir la página {n} a tamaño completo",
    transcript: "Transcripción",
    transcriptIntro: "El texto de cada página, en orden: para quien usa un lector de pantalla y para quien prefiere leerlo.",
    noText: "Esta página no tiene texto.",
    translatedNote: "Textos traducidos automáticamente del {lang}: los globos siguen en el idioma original.",
    originalNote: "Los textos están en {lang}: la traducción llegará en unos minutos.",
    moreTitle: "Más cómics",
    allComics: "Todos los cómics",
    allNews: "Todas las noticias",
    unavailable: "Los cómics aún no están disponibles: vuelve a intentarlo en unos minutos.",
  },
  hub: {
    title: "Cómics de Origins TCG",
    metaTitle: "Cómics de Origins TCG de los creadores de la comunidad",
    description: "Cómics sobre Origins TCG dibujados por los creadores de la comunidad de OriginsMeta: noticias, historias y vida de juego, con los textos en español, inglés e italiano.",
    intro: "Cómics sobre Origins TCG dibujados por los creadores de la comunidad: noticias, historias y vida de juego. También salen entre las noticias.",
    empty: "Aún no hay cómics: el primero está en camino.",
  },
  cta: {
    title: "Publica un cómic",
    text: "Como Creator puedes publicar tus cómics entre las noticias: páginas, portada y textos, traducidos por el sitio a los otros dos idiomas.",
    button: "Publica un cómic",
  },
  newTitle: "Publica un cómic",
  newDescription: "Publica un cómic sobre Origins TCG en OriginsMeta: páginas, portada y textos, entre las noticias, con tu nombre y traducido automáticamente.",
  newIntro: "Páginas, portada y textos: el cómic sale entre las noticias, con tu nombre y una página propia. El sitio traduce el título, la presentación y los textos de las páginas a los otros dos idiomas.",
  editTitle: "Edita el cómic",
  notAllowed: {
    title: "Los cómics son para los Creators y el Staff",
    text: "Publicar cómics entre las noticias es para los roles Creator y Staff. Si dibujas cómics sobre Origins TCG, escribe al staff desde tus mensajes.",
  },
  editor: {
    lang: "Idioma de los textos",
    langHint: "El idioma de los globos y de los textos de abajo. El sitio traduce el título, la presentación y los textos de las páginas a los otros dos idiomas.",
    title: "Título",
    summary: "Presentación",
    summaryHint: "2 o 3 frases, de {min} a {max} caracteres: aparecen en la lista de noticias, en la portada del sitio y al compartir el enlace.",
    cover: "Portada",
    coverHint: "16:9, al menos {minw} × {minh} px (lo ideal es {w} × {h}), PNG, JPG o WebP: la recortamos al centro en 16:9. Aparece en la lista de noticias, en la portada del sitio y al compartir el enlace.",
    coverUpload: "Sube la portada",
    coverReplace: "Cambia la portada",
    coverAlt: "Portada del cómic",
    uploading: "Subiendo…",
    pages: "Páginas",
    pagesHint: "Imágenes verticales que se leen de arriba abajo: {w} px de ancho y hasta {h} px de alto (9:16). Una historia más larga va en más imágenes, hasta {max}; también sirven viñetas sueltas de 1080 × 1350 (4:5). PNG, JPG o WebP de hasta 20 MB: el sitio las reduce y las convierte.",
    pagesAdd: "Añade páginas",
    pagesUploading: "Subiendo la página {n} de {total}…",
    pagesCount: "{n} de {max} páginas",
    pageLabel: "Página {n}",
    pageText: "Texto de la página {n}",
    pageTextHint: "Diálogos, textos de apoyo y onomatopeyas, en orden de lectura. Opcional, pero es lo que leen los lectores de pantalla y Google, y lo que traducimos.",
    pageUp: "Subir",
    pageDown: "Bajar",
    pageRemove: "Quitar",
    uploadErrors: {
      type: "Este archivo no es una imagen PNG, JPG o WebP.",
      tooBig: "La imagen pesa demasiado incluso después de comprimirla: prueba con una más ligera.",
      upload: "La subida no salió bien: revisa la conexión y vuelve a intentarlo.",
      limit: "Llegaste al límite de imágenes subidas: elimina un cómic que ya no necesites, o escribe al staff.",
      source: "Este archivo supera los 20 MB: exporta una versión más ligera.",
      full: "Un cómic tiene como máximo {max} páginas.",
    },
    rights: "Solo dibujos tuyos o que tengas derecho a publicar, y ninguna carta que aún no se haya anunciado.",
    saveDraft: "Guardar borrador",
    publish: "Publicar",
    update: "Guardar los cambios",
    unpublish: "Volver a borradores",
    saving: "Guardando…",
    saved: "Borrador guardado.",
    statusDraft: "Borrador: solo tú puedes verlo.",
    statusPublished: "Publicado: cada cambio se publica al momento.",
    statusHidden: "Oculto por el staff: escribe al staff desde tus mensajes para saber por qué.",
    counter: "{n}/{max}",
    consent: "Al publicar, el cómic sale entre las noticias con tu nombre, con las traducciones automáticas de los textos que hace el sitio, y lo anunciamos en nuestro Discord. Puedes volver a dejarlo como borrador o eliminarlo cuando quieras.",
  },
  errors: {
    lang: "Elige el idioma de los textos.",
    title: "Título: de {min} a {max} caracteres en una línea (a un borrador le basta uno).",
    summary: "Presentación: de {min} a {max} caracteres para publicar (un borrador puede dejarla vacía).",
    pages: "Páginas: de 1 a {max} para publicar.",
    page: "Página {n}: la imagen o su texto no sirven. Súbela de nuevo.",
    cover: "Sube una portada para publicar.",
    notLoggedIn: "Inicia sesión para publicar un cómic.",
    forbidden: "Publicar cómics es para los Creators y el Staff.",
    disabled: "Las cuentas están desactivadas en esta copia del sitio.",
    unavailable: "Los cómics aún no están disponibles: vuelve a intentarlo en unos minutos.",
    comic_daily_limit: "Ya publicaste 3 cómics nuevos en las últimas 24 horas: guarda este como borrador y publícalo mañana.",
    comic_limit: "Llegaste a 500 cómics: elimina uno antiguo para publicar uno nuevo.",
    comic_rate: "Empezaste 10 cómics en las últimas 24 horas: vuelve a intentarlo mañana.",
    comic_hidden: "El staff ocultó este cómic: escribe al staff desde tus mensajes.",
    comic_hidden_recent: "El staff ocultó uno de tus cómics en las últimas 24 horas: podrás volver a publicar mañana. Mientras tanto, guarda este como borrador.",
    comic_status: "Este cambio es solo para el staff.",
    comic_file: "No se encuentra una de las imágenes: súbela de nuevo.",
    comic_translation: "No se pudo guardar la traducción: los textos se quedan como están.",
    comic_reserved_fields: "Este cambio no está permitido.",
    duplicate: "Algo salió mal con la dirección del cómic: vuelve a intentarlo.",
    db: "No se pudo guardar: vuelve a intentarlo en un momento.",
    tooFast: "Espera {n} segundos antes de volver a guardar.",
  },
  account: {
    title: "Mis cómics",
    intro: "Borradores, cómics publicados y cómics ocultos por el staff. En el sitio, entre las noticias, solo aparecen los publicados.",
    none: "Aún no hay cómics.",
    write: "Publica un cómic",
    view: "Ver",
    edit: "Editar",
    status: { draft: "Borrador", published: "Publicado", hidden: "Oculto por el staff" },
  },
  owner: {
    edit: "Editar",
    unpublish: "Volver a borradores",
    delete: "Eliminar",
    confirmDelete: "¿Eliminar este cómic y sus imágenes? No se puede deshacer.",
    hide: "Ocultar (staff)",
    unhide: "Volver a publicar (staff)",
  },
  profile: {
    title: "Cómics",
  },
  privacy:
    "Cómics. Los Creators y el Staff pueden publicar cómics entre las noticias. Las páginas y la portada se guardan como las demás imágenes que subes al sitio (mira arriba: tu navegador las reduce y las vuelve a codificar, quitando datos como la ubicación); el título, la presentación y los textos de las páginas son públicos en la página del cómic, con tu nombre y el enlace a tu perfil, y el sitio traduce el título, la presentación y los textos a los otros dos idiomas con el mismo servicio que usa para las guías. Cuando sale un cómic, quien te sigue recibe un aviso y nuestro Discord lo anuncia. Puedes editar un cómic, volver a dejarlo como borrador o eliminarlo cuando quieras: al eliminarlo se borran también sus imágenes. El staff puede ocultar un cómic que no respete las reglas del sitio.",
};

export const comicLabels: Record<Locale, ComicLabels> = { en, it, es };

/** Nomi delle lingue nella lingua della pagina, per le note sulla traduzione dei testi ("l'originale è in spagnolo"). */
export const COMIC_LANG_NAMES: Record<Locale, Record<Locale, string>> = {
  en: { en: "English", it: "Italian", es: "Spanish" },
  it: { en: "inglese", it: "italiano", es: "spagnolo" },
  es: { en: "inglés", it: "italiano", es: "español" },
};
