import type { Locale } from "./i18n";

/**
 * Testi dei fumetti dei Creator (pacchetto FUMETTI, 29/09/2026): voci fra le news, pagina del fumetto, elenco
 * /news/comics, modulo di pubblicazione, errori, "I miei fumetti" in /account, comandi del proprietario e dello staff,
 * paragrafo della privacy. Un modulo solo nelle tre lingue, come communityGuideLabels.ts; `en` è il tipo di riferimento.
 * Segnaposto fra graffe ({name}, {date}, {n}, {total}, {max}, {min}, {minw}…): li riempie `fillLabel` (deckQuality.ts).
 * Nessun import a runtime: comics.test.ts lo carica con `node --test` e controlla chiavi e segnaposto.
 * Spagnolo neutro con il tú (docs/spagnolo.md): "cómic" e "página", mai parole che cambiano da paese a paese.
 */
const en = {
  /** pastiglia accanto alla data nelle news e post-it della home */
  pill: "Comic",
  by: "Comic by {name}",
  read: "Read the comic",
  page: {
    /** in coda al titolo per la SERP ("{title} · Origins TCG comic") */
    metaSuffix: "Origins TCG comic",
    published: "Published on {date}",
    updated: "updated on {date}",
    pagesOne: "1 page",
    pagesMany: "{n} pages",
    pageAlt: "Page {n} of {total}",
    pageAltText: "Page {n} of {total}. {text}",
    open: "Open page {n} full size",
    transcript: "Transcript",
    transcriptIntro: "The text of every page, in order: for screen readers and for anyone who prefers to read it.",
    noText: "No text on this page.",
    translatedNote: "Texts translated automatically from {lang}: the balloons stay in the original language.",
    originalNote: "The texts are in {lang}: the translation will be ready in a few minutes.",
    moreTitle: "More comics",
    allComics: "All the comics",
    allNews: "All the news",
    unavailable: "Comics are not available yet: try again in a few minutes.",
  },
  hub: {
    title: "Origins TCG comics",
    metaTitle: "Origins TCG comics by the community creators",
    description: "Comics about Origins TCG drawn by the creators of the OriginsMeta community: news, stories and life in the game, with the texts in English, Italian, Spanish and French.",
    intro: "Comics about Origins TCG drawn by the creators of the community: news, stories and life in the game. They also come out among the news.",
    empty: "No comics yet: the first one is on its way.",
  },
  /** riquadro in /news per chi può pubblicare (Creator e Staff), deciso nel browser */
  cta: {
    title: "Publish a comic",
    text: "As a Creator you can publish your comics among the news: pages, cover and texts, translated by the site into the other languages of the site.",
    button: "Publish a comic",
  },
  newTitle: "Publish a comic",
  newDescription: "Publish an Origins TCG comic on OriginsMeta: pages, cover and texts, among the news, under your name and translated automatically.",
  newIntro: "Pages, cover and texts: the comic comes out among the news, under your name, with its own page. The site translates the title, the presentation and the texts of the pages into the other languages of the site.",
  editTitle: "Edit the comic",
  notAllowed: {
    title: "Comics are for Creators and Staff",
    text: "Publishing comics among the news is for the Creator and Staff roles. If you draw comics about Origins TCG, write to the staff from your messages.",
  },
  editor: {
    lang: "Language of the texts",
    langHint: "The language of the balloons and of the texts below. The site translates the title, the presentation and the page texts into the other languages of the site; if you also drew the comic in another language, add that version further down.",
    title: "Title",
    summary: "Presentation",
    summaryHint: "2 or 3 sentences, from {min} to {max} characters: they appear in the news list, on the home page and when the link is shared.",
    cover: "Cover",
    coverHint: "16:9, at least {minw} × {minh} px ({w} × {h} is ideal), PNG, JPG or WebP: we crop it to 16:9 from the center. It appears in the news list, on the home page and when the link is shared.",
    coverUpload: "Upload the cover",
    coverReplace: "Change the cover",
    coverAlt: "Cover of the comic",
    uploading: "Uploading…",
    pages: "Pages",
    pagesHint: "Vertical images read from top to bottom: {w} px wide and up to {h} px tall (9:16). A longer story goes in more images, up to {max}; single panels of 1080 × 1350 (4:5) are fine too. PNG, JPG or WebP up to 20 MB: the site shrinks and converts them.",
    pagesAdd: "Add pages",
    pagesUploading: "Uploading page {n} of {total}…",
    pagesCount: "{n} of {max} pages",
    pageLabel: "Page {n}",
    pageText: "Text of page {n}",
    pageTextHint: "Dialogues, captions and sound effects, in reading order. Optional, but screen readers and Google read this, and it's what we translate.",
    pageUp: "Move up",
    pageDown: "Move down",
    pageRemove: "Remove",
    uploadErrors: {
      type: "This file is not a PNG, JPG or WebP image.",
      tooBig: "The image is too heavy even after compression: try a lighter one.",
      upload: "The upload didn't go through: check your connection and try again.",
      limit: "You have reached the limit of uploaded images: delete a comic you no longer need, or write to the staff.",
      source: "This file is over 20 MB: export a lighter version.",
      full: "A comic has at most {max} pages.",
    },
    rights: "Only drawings that are yours or that you have the right to publish, and no cards that haven't been announced yet.",
    saveDraft: "Save draft",
    publish: "Publish",
    update: "Save changes",
    unpublish: "Move back to drafts",
    saving: "Saving…",
    saved: "Draft saved.",
    statusDraft: "Draft: only you can see it.",
    statusPublished: "Published: every change goes online right away.",
    statusHidden: "Hidden by the staff: write to the staff from your messages to know why.",
    counter: "{n}/{max}",
    consent: "Publishing puts the comic online among the news, under your name, with the site's automatic translations of the texts, and announces it on our Discord. You can move it back to drafts or delete it whenever you want.",
    /** versioni disegnate nelle altre lingue (30/09/2026); {lang} = nome della lingua ("Italian") */
    editions: {
      title: "Versions drawn in other languages",
      hint: "Did you also draw the comic in another language, with the balloons rewritten? Add that version here: its readers see its pages, title and presentation instead of the automatic translation. It stays one comic, one news item, one address.",
      heading: "{lang} version",
      add: "Add the {lang} version",
      remove: "Remove the {lang} version",
      confirmRemove: "Remove the {lang} version and its images?",
      cover: "Cover of this version (optional)",
      coverHint: "Only if the cover has text on it: without one, the comic's cover is used.",
    },
  },
  errors: {
    lang: "Choose the language of the texts.",
    title: "Title: from {min} to {max} characters on one line (a draft needs just one).",
    summary: "Presentation: from {min} to {max} characters to publish (a draft can leave it empty).",
    pages: "Pages: from 1 to {max} to publish.",
    page: "Page {n}: the image or its text can't be used. Upload it again.",
    cover: "Upload a cover to publish.",
    notLoggedIn: "Sign in to publish a comic.",
    forbidden: "Publishing comics is for Creators and Staff.",
    disabled: "Accounts are switched off on this copy of the site.",
    unavailable: "Comics are not available yet: try again in a few minutes.",
    comic_daily_limit: "You have already published 3 new comics in the last 24 hours: save this one as a draft and publish it tomorrow.",
    comic_limit: "You have reached 500 comics: delete an old one to publish a new one.",
    comic_rate: "You have started 10 comics in the last 24 hours: try again tomorrow.",
    comic_hidden: "The staff has hidden this comic: write to the staff from your messages.",
    comic_hidden_recent: "The staff hid one of your comics in the last 24 hours: you can publish again tomorrow. Save this one as a draft meanwhile.",
    comic_status: "This change is for the staff only.",
    comic_file: "One of the images can't be found: upload it again.",
    comic_translation: "The translation couldn't be saved: the texts stay as they are.",
    comic_reserved_fields: "This change is not allowed.",
    duplicate: "Something went wrong with the address of the comic: try again.",
    db: "Saving failed: try again in a moment.",
    /** {n} = secondi da aspettare */
    tooFast: "Wait {n} seconds before saving again.",
    editions: "The versions in other languages can't be used: check them and try again.",
    edition_title: "{lang} version, title: from {min} to {max} characters on one line.",
    edition_summary: "{lang} version, presentation: from {min} to {max} characters to publish.",
    edition_pages: "{lang} version, pages: from 1 to {max} to publish.",
    edition_page: "{lang} version, page {n}: the image or its text can't be used. Upload it again.",
    edition_cover: "{lang} version: the cover can't be used. Upload it again.",
  },
  account: {
    title: "My comics",
    intro: "Drafts, published comics and comics hidden by the staff. Only the published ones appear on the site, among the news.",
    none: "No comics yet.",
    write: "Publish a comic",
    view: "View",
    edit: "Edit",
    status: { draft: "Draft", published: "Published", hidden: "Hidden by the staff" },
  },
  owner: {
    edit: "Edit",
    unpublish: "Move back to drafts",
    delete: "Delete",
    confirmDelete: "Delete this comic and its images? This can't be undone.",
    hide: "Hide (staff)",
    unhide: "Put back online (staff)",
  },
  profile: {
    title: "Comics",
  },
  /** paragrafo della privacy (#community-comics) */
  privacy:
    "Comics. Creators and Staff can publish comics among the news. The pages and the cover are stored like the other images you upload on the site (see above: your browser shrinks and re-encodes them, removing data such as the location); the title, the presentation and the texts of the pages are public on the comic's page, with your name and a link to your profile, and the site translates the title, the presentation and the texts into the other languages of the site with the same service used for the guides. When a comic comes out, whoever follows you receives a notice and our Discord announces it. You can edit a comic, move it back to drafts or delete it at any time: deleting it deletes its images too. The staff can hide a comic that breaks the site rules.",
};

export type ComicLabels = typeof en;

const it: ComicLabels = {
  pill: "Fumetto",
  by: "Fumetto di {name}",
  read: "Leggi il fumetto",
  page: {
    metaSuffix: "fumetto di Origins TCG",
    published: "Pubblicato il {date}",
    updated: "aggiornato il {date}",
    pagesOne: "1 tavola",
    pagesMany: "{n} tavole",
    pageAlt: "Tavola {n} di {total}",
    pageAltText: "Tavola {n} di {total}. {text}",
    open: "Apri la tavola {n} a grandezza piena",
    transcript: "Trascrizione",
    transcriptIntro: "Il testo di ogni tavola, in ordine: per chi usa un lettore di schermo e per chi preferisce leggerlo.",
    noText: "Nessun testo in questa tavola.",
    translatedNote: "Testi tradotti in automatico (l'originale è in {lang}): i balloon restano nella lingua originale.",
    originalNote: "I testi sono in {lang}: la traduzione arriva fra qualche minuto.",
    moreTitle: "Altri fumetti",
    allComics: "Tutti i fumetti",
    allNews: "Tutte le news",
    unavailable: "I fumetti non sono ancora disponibili: riprova fra qualche minuto.",
  },
  hub: {
    title: "Fumetti di Origins TCG",
    metaTitle: "Fumetti di Origins TCG dei creator della community",
    description: "Fumetti su Origins TCG disegnati dai creator della community di OriginsMeta: notizie, storie e vita di gioco, con i testi in italiano, inglese e spagnolo.",
    intro: "Fumetti su Origins TCG disegnati dai creator della community: notizie, storie e vita di gioco. Escono anche fra le news.",
    empty: "Ancora nessun fumetto: il primo sta arrivando.",
  },
  cta: {
    title: "Pubblica un fumetto",
    text: "Come Creator puoi pubblicare i tuoi fumetti fra le news: tavole, copertina e testi, tradotti dal sito nelle altre lingue del sito.",
    button: "Pubblica un fumetto",
  },
  newTitle: "Pubblica un fumetto",
  newDescription: "Pubblica un fumetto su Origins TCG su OriginsMeta: tavole, copertina e testi, fra le news, con il tuo nome e tradotto in automatico.",
  newIntro: "Tavole, copertina e testi: il fumetto esce fra le news, con il tuo nome e una pagina sua. Il sito traduce titolo, presentazione e testi delle tavole nelle altre lingue del sito.",
  editTitle: "Modifica il fumetto",
  notAllowed: {
    title: "I fumetti sono per i Creator e lo Staff",
    text: "Pubblicare fumetti fra le news è per i ruoli Creator e Staff. Se disegni fumetti su Origins TCG, scrivi allo staff dai tuoi messaggi.",
  },
  editor: {
    lang: "Lingua dei testi",
    langHint: "La lingua dei balloon e dei testi qui sotto. Il sito traduce titolo, presentazione e testi delle tavole nelle altre lingue del sito; se hai disegnato il fumetto anche in un'altra lingua, aggiungi quella versione più in basso.",
    title: "Titolo",
    summary: "Presentazione",
    summaryHint: "2 o 3 frasi, da {min} a {max} caratteri: compaiono nell'elenco delle news, in home e quando si condivide il link.",
    cover: "Copertina",
    coverHint: "16:9, almeno {minw} × {minh} px (l'ideale è {w} × {h}), PNG, JPG o WebP: la ritagliamo al centro in 16:9. Compare nell'elenco delle news, in home e quando si condivide il link.",
    coverUpload: "Carica la copertina",
    coverReplace: "Cambia la copertina",
    coverAlt: "Copertina del fumetto",
    uploading: "Caricamento…",
    pages: "Tavole",
    pagesHint: "Immagini verticali da leggere dall'alto in basso: larghe {w} px e alte fino a {h} px (9:16). Una storia più lunga va in più immagini, fino a {max}; vanno bene anche vignette singole da 1080 × 1350 (4:5). PNG, JPG o WebP fino a 20 MB: il sito le riduce e le converte.",
    pagesAdd: "Aggiungi tavole",
    pagesUploading: "Caricamento della tavola {n} di {total}…",
    pagesCount: "{n} di {max} tavole",
    pageLabel: "Tavola {n}",
    pageText: "Testo della tavola {n}",
    pageTextHint: "Dialoghi, didascalie ed effetti sonori, nell'ordine di lettura. Facoltativo, ma è quello che leggono i lettori di schermo e Google, ed è quello che traduciamo.",
    pageUp: "Sposta su",
    pageDown: "Sposta giù",
    pageRemove: "Togli",
    uploadErrors: {
      type: "Questo file non è un'immagine PNG, JPG o WebP.",
      tooBig: "L'immagine è troppo pesante anche dopo la compressione: provane una più leggera.",
      upload: "Il caricamento non è andato a buon fine: controlla la connessione e riprova.",
      limit: "Hai raggiunto il limite di immagini caricate: elimina un fumetto che non ti serve più, o scrivi allo staff.",
      source: "Questo file supera i 20 MB: esportane una versione più leggera.",
      full: "Un fumetto ha al massimo {max} tavole.",
    },
    rights: "Solo disegni tuoi o che hai il diritto di pubblicare, e niente carte non ancora annunciate.",
    saveDraft: "Salva bozza",
    publish: "Pubblica",
    update: "Salva le modifiche",
    unpublish: "Riporta tra le bozze",
    saving: "Salvataggio…",
    saved: "Bozza salvata.",
    statusDraft: "Bozza: la vedi solo tu.",
    statusPublished: "Pubblicato: ogni modifica va subito online.",
    statusHidden: "Nascosto dallo staff: scrivi allo staff dai tuoi messaggi per sapere perché.",
    counter: "{n}/{max}",
    consent: "Pubblicando, il fumetto va online fra le news con il tuo nome, con le traduzioni automatiche dei testi fatte dal sito, e lo annunciamo sul nostro Discord. Puoi riportarlo tra le bozze o eliminarlo quando vuoi.",
    editions: {
      title: "Versioni disegnate in altre lingue",
      hint: "Hai disegnato il fumetto anche in un'altra lingua, con i balloon riscritti? Aggiungi qui quella versione: chi legge in quella lingua vede le sue tavole, il suo titolo e la sua presentazione al posto della traduzione automatica. Resta un fumetto solo, una news sola, un indirizzo solo.",
      heading: "Versione in {lang}",
      add: "Aggiungi la versione in {lang}",
      remove: "Togli la versione in {lang}",
      confirmRemove: "Togliere la versione in {lang} e le sue immagini?",
      cover: "Copertina di questa versione (facoltativa)",
      coverHint: "Solo se la copertina ha delle scritte: senza, vale quella del fumetto.",
    },
  },
  errors: {
    lang: "Scegli la lingua dei testi.",
    title: "Titolo: da {min} a {max} caratteri su una riga (a una bozza ne basta uno).",
    summary: "Presentazione: da {min} a {max} caratteri per pubblicare (una bozza può lasciarla vuota).",
    pages: "Tavole: da 1 a {max} per pubblicare.",
    page: "Tavola {n}: l'immagine o il suo testo non vanno bene. Caricala di nuovo.",
    cover: "Carica una copertina per pubblicare.",
    notLoggedIn: "Accedi per pubblicare un fumetto.",
    forbidden: "Pubblicare fumetti è per i Creator e lo Staff.",
    disabled: "Gli account sono spenti in questa copia del sito.",
    unavailable: "I fumetti non sono ancora disponibili: riprova fra qualche minuto.",
    comic_daily_limit: "Hai già pubblicato 3 fumetti nuovi nelle ultime 24 ore: salva questo come bozza e pubblicalo domani.",
    comic_limit: "Hai raggiunto 500 fumetti: eliminane uno vecchio per pubblicarne uno nuovo.",
    comic_rate: "Hai iniziato 10 fumetti nelle ultime 24 ore: riprova domani.",
    comic_hidden: "Lo staff ha nascosto questo fumetto: scrivi allo staff dai tuoi messaggi.",
    comic_hidden_recent: "Lo staff ha nascosto un tuo fumetto nelle ultime 24 ore: potrai pubblicare di nuovo domani. Intanto salva questo come bozza.",
    comic_status: "Questa modifica è riservata allo staff.",
    comic_file: "Una delle immagini non si trova: caricala di nuovo.",
    comic_translation: "Non è stato possibile salvare la traduzione: i testi restano come sono.",
    comic_reserved_fields: "Questa modifica non è consentita.",
    duplicate: "Qualcosa è andato storto con l'indirizzo del fumetto: riprova.",
    db: "Salvataggio non riuscito: riprova fra un momento.",
    tooFast: "Aspetta {n} secondi prima di salvare di nuovo.",
    editions: "Le versioni nelle altre lingue non vanno bene: controllale e riprova.",
    edition_title: "Versione in {lang}, titolo: da {min} a {max} caratteri su una riga.",
    edition_summary: "Versione in {lang}, presentazione: da {min} a {max} caratteri per pubblicare.",
    edition_pages: "Versione in {lang}, tavole: da 1 a {max} per pubblicare.",
    edition_page: "Versione in {lang}, tavola {n}: l'immagine o il suo testo non vanno bene. Caricala di nuovo.",
    edition_cover: "Versione in {lang}: la copertina non va bene. Caricala di nuovo.",
  },
  account: {
    title: "I miei fumetti",
    intro: "Bozze, fumetti pubblicati e fumetti nascosti dallo staff. Sul sito, fra le news, compaiono solo i pubblicati.",
    none: "Ancora nessun fumetto.",
    write: "Pubblica un fumetto",
    view: "Apri",
    edit: "Modifica",
    status: { draft: "Bozza", published: "Pubblicato", hidden: "Nascosto dallo staff" },
  },
  owner: {
    edit: "Modifica",
    unpublish: "Riporta tra le bozze",
    delete: "Elimina",
    confirmDelete: "Eliminare questo fumetto e le sue immagini? Non si può annullare.",
    hide: "Nascondi (staff)",
    unhide: "Rimetti online (staff)",
  },
  profile: {
    title: "Fumetti",
  },
  privacy:
    "Fumetti. I Creator e lo Staff possono pubblicare fumetti fra le news. Tavole e copertina si salvano come le altre immagini che carichi sul sito (vedi sopra: il tuo browser le riduce e le ricodifica, togliendo dati come la posizione); titolo, presentazione e testi delle tavole sono pubblici nella pagina del fumetto, con il tuo nome e il link al tuo profilo, e il sito traduce titolo, presentazione e testi nelle altre lingue del sito con lo stesso servizio usato per le guide. Quando esce un fumetto, chi ti segue riceve un avviso e il nostro Discord lo annuncia. Puoi modificare un fumetto, riportarlo tra le bozze o eliminarlo quando vuoi: eliminandolo si cancellano anche le sue immagini. Lo staff può nascondere un fumetto che non rispetta le regole del sito.",
};

const es: ComicLabels = {
  pill: "Cómic",
  by: "Cómic de {name}",
  read: "Lee el cómic",
  page: {
    metaSuffix: "cómic de Origins TCG",
    published: "Publicado el {date}",
    updated: "actualizado el {date}",
    pagesOne: "1 página",
    pagesMany: "{n} páginas",
    pageAlt: "Página {n} de {total}",
    pageAltText: "Página {n} de {total}. {text}",
    open: "Abrir la página {n} a tamaño completo",
    transcript: "Transcripción",
    transcriptIntro: "El texto de cada página, en orden: para quien usa un lector de pantalla y para quien prefiere leerlo.",
    noText: "Esta página no tiene texto.",
    translatedNote: "Textos traducidos automáticamente del {lang}: los globos siguen en el idioma original.",
    originalNote: "Los textos están en {lang}: la traducción llegará en unos minutos.",
    moreTitle: "Más cómics",
    allComics: "Todos los cómics",
    allNews: "Todas las noticias",
    unavailable: "Los cómics aún no están disponibles: vuelve a intentarlo en unos minutos.",
  },
  hub: {
    title: "Cómics de Origins TCG",
    metaTitle: "Cómics de Origins TCG de los creadores de la comunidad",
    description: "Cómics sobre Origins TCG dibujados por los creadores de la comunidad de OriginsMeta: noticias, historias y vida de juego, con los textos en español, inglés e italiano.",
    intro: "Cómics sobre Origins TCG dibujados por los creadores de la comunidad: noticias, historias y vida de juego. También salen entre las noticias.",
    empty: "Aún no hay cómics: el primero está en camino.",
  },
  cta: {
    title: "Publica un cómic",
    text: "Como Creator puedes publicar tus cómics entre las noticias: páginas, portada y textos, traducidos por el sitio a los otros idiomas del sitio.",
    button: "Publica un cómic",
  },
  newTitle: "Publica un cómic",
  newDescription: "Publica un cómic sobre Origins TCG en OriginsMeta: páginas, portada y textos, entre las noticias, con tu nombre y traducido automáticamente.",
  newIntro: "Páginas, portada y textos: el cómic sale entre las noticias, con tu nombre y una página propia. El sitio traduce el título, la presentación y los textos de las páginas a los otros idiomas del sitio.",
  editTitle: "Edita el cómic",
  notAllowed: {
    title: "Los cómics son para los Creators y el Staff",
    text: "Publicar cómics entre las noticias es para los roles Creator y Staff. Si dibujas cómics sobre Origins TCG, escribe al staff desde tus mensajes.",
  },
  editor: {
    lang: "Idioma de los textos",
    langHint: "El idioma de los globos y de los textos de abajo. El sitio traduce el título, la presentación y los textos de las páginas a los otros idiomas del sitio; si también dibujaste el cómic en otro idioma, añade esa versión más abajo.",
    title: "Título",
    summary: "Presentación",
    summaryHint: "2 o 3 frases, de {min} a {max} caracteres: aparecen en la lista de noticias, en la portada del sitio y al compartir el enlace.",
    cover: "Portada",
    coverHint: "16:9, al menos {minw} × {minh} px (lo ideal es {w} × {h}), PNG, JPG o WebP: la recortamos al centro en 16:9. Aparece en la lista de noticias, en la portada del sitio y al compartir el enlace.",
    coverUpload: "Sube la portada",
    coverReplace: "Cambia la portada",
    coverAlt: "Portada del cómic",
    uploading: "Subiendo…",
    pages: "Páginas",
    pagesHint: "Imágenes verticales que se leen de arriba abajo: {w} px de ancho y hasta {h} px de alto (9:16). Una historia más larga va en más imágenes, hasta {max}; también sirven viñetas sueltas de 1080 × 1350 (4:5). PNG, JPG o WebP de hasta 20 MB: el sitio las reduce y las convierte.",
    pagesAdd: "Añade páginas",
    pagesUploading: "Subiendo la página {n} de {total}…",
    pagesCount: "{n} de {max} páginas",
    pageLabel: "Página {n}",
    pageText: "Texto de la página {n}",
    pageTextHint: "Diálogos, textos de apoyo y onomatopeyas, en orden de lectura. Opcional, pero es lo que leen los lectores de pantalla y Google, y lo que traducimos.",
    pageUp: "Subir",
    pageDown: "Bajar",
    pageRemove: "Quitar",
    uploadErrors: {
      type: "Este archivo no es una imagen PNG, JPG o WebP.",
      tooBig: "La imagen pesa demasiado incluso después de comprimirla: prueba con una más ligera.",
      upload: "La subida no salió bien: revisa la conexión y vuelve a intentarlo.",
      limit: "Llegaste al límite de imágenes subidas: elimina un cómic que ya no necesites, o escribe al staff.",
      source: "Este archivo supera los 20 MB: exporta una versión más ligera.",
      full: "Un cómic tiene como máximo {max} páginas.",
    },
    rights: "Solo dibujos tuyos o que tengas derecho a publicar, y ninguna carta que aún no se haya anunciado.",
    saveDraft: "Guardar borrador",
    publish: "Publicar",
    update: "Guardar los cambios",
    unpublish: "Volver a borradores",
    saving: "Guardando…",
    saved: "Borrador guardado.",
    statusDraft: "Borrador: solo tú puedes verlo.",
    statusPublished: "Publicado: cada cambio se publica al momento.",
    statusHidden: "Oculto por el staff: escribe al staff desde tus mensajes para saber por qué.",
    counter: "{n}/{max}",
    consent: "Al publicar, el cómic sale entre las noticias con tu nombre, con las traducciones automáticas de los textos que hace el sitio, y lo anunciamos en nuestro Discord. Puedes volver a dejarlo como borrador o eliminarlo cuando quieras.",
    editions: {
      title: "Versiones dibujadas en otros idiomas",
      hint: "¿Dibujaste el cómic también en otro idioma, con los globos reescritos? Añade aquí esa versión: quien lee en ese idioma ve sus páginas, su título y su presentación en lugar de la traducción automática. Sigue siendo un solo cómic, una sola noticia, una sola dirección.",
      heading: "Versión en {lang}",
      add: "Añade la versión en {lang}",
      remove: "Quita la versión en {lang}",
      confirmRemove: "¿Quitar la versión en {lang} y sus imágenes?",
      cover: "Portada de esta versión (opcional)",
      coverHint: "Solo si la portada lleva texto: si no, se usa la del cómic.",
    },
  },
  errors: {
    lang: "Elige el idioma de los textos.",
    title: "Título: de {min} a {max} caracteres en una línea (a un borrador le basta uno).",
    summary: "Presentación: de {min} a {max} caracteres para publicar (un borrador puede dejarla vacía).",
    pages: "Páginas: de 1 a {max} para publicar.",
    page: "Página {n}: la imagen o su texto no sirven. Súbela de nuevo.",
    cover: "Sube una portada para publicar.",
    notLoggedIn: "Inicia sesión para publicar un cómic.",
    forbidden: "Publicar cómics es para los Creators y el Staff.",
    disabled: "Las cuentas están desactivadas en esta copia del sitio.",
    unavailable: "Los cómics aún no están disponibles: vuelve a intentarlo en unos minutos.",
    comic_daily_limit: "Ya publicaste 3 cómics nuevos en las últimas 24 horas: guarda este como borrador y publícalo mañana.",
    comic_limit: "Llegaste a 500 cómics: elimina uno antiguo para publicar uno nuevo.",
    comic_rate: "Empezaste 10 cómics en las últimas 24 horas: vuelve a intentarlo mañana.",
    comic_hidden: "El staff ocultó este cómic: escribe al staff desde tus mensajes.",
    comic_hidden_recent: "El staff ocultó uno de tus cómics en las últimas 24 horas: podrás volver a publicar mañana. Mientras tanto, guarda este como borrador.",
    comic_status: "Este cambio es solo para el staff.",
    comic_file: "No se encuentra una de las imágenes: súbela de nuevo.",
    comic_translation: "No se pudo guardar la traducción: los textos se quedan como están.",
    comic_reserved_fields: "Este cambio no está permitido.",
    duplicate: "Algo salió mal con la dirección del cómic: vuelve a intentarlo.",
    db: "No se pudo guardar: vuelve a intentarlo en un momento.",
    tooFast: "Espera {n} segundos antes de volver a guardar.",
    editions: "Las versiones en otros idiomas no sirven: revísalas y vuelve a intentarlo.",
    edition_title: "Versión en {lang}, título: de {min} a {max} caracteres en una línea.",
    edition_summary: "Versión en {lang}, presentación: de {min} a {max} caracteres para publicar.",
    edition_pages: "Versión en {lang}, páginas: de 1 a {max} para publicar.",
    edition_page: "Versión en {lang}, página {n}: la imagen o su texto no sirven. Súbela de nuevo.",
    edition_cover: "Versión en {lang}: la portada no sirve. Súbela de nuevo.",
  },
  account: {
    title: "Mis cómics",
    intro: "Borradores, cómics publicados y cómics ocultos por el staff. En el sitio, entre las noticias, solo aparecen los publicados.",
    none: "Aún no hay cómics.",
    write: "Publica un cómic",
    view: "Ver",
    edit: "Editar",
    status: { draft: "Borrador", published: "Publicado", hidden: "Oculto por el staff" },
  },
  owner: {
    edit: "Editar",
    unpublish: "Volver a borradores",
    delete: "Eliminar",
    confirmDelete: "¿Eliminar este cómic y sus imágenes? No se puede deshacer.",
    hide: "Ocultar (staff)",
    unhide: "Volver a publicar (staff)",
  },
  profile: {
    title: "Cómics",
  },
  privacy:
    "Cómics. Los Creators y el Staff pueden publicar cómics entre las noticias. Las páginas y la portada se guardan como las demás imágenes que subes al sitio (mira arriba: tu navegador las reduce y las vuelve a codificar, quitando datos como la ubicación); el título, la presentación y los textos de las páginas son públicos en la página del cómic, con tu nombre y el enlace a tu perfil, y el sitio traduce el título, la presentación y los textos a los otros idiomas del sitio con el mismo servicio que usa para las guías. Cuando sale un cómic, quien te sigue recibe un aviso y nuestro Discord lo anuncia. Puedes editar un cómic, volver a dejarlo como borrador o eliminarlo cuando quieras: al eliminarlo se borran también sus imágenes. El staff puede ocultar un cómic que no respete las reglas del sitio.",
};

/** Francese (07/10/2026, docs/francese.md): "vous", i fumetti sono "BD" e le pagine "planches"; spazio insecabile prima di : ; ? ! */
const fr: ComicLabels = {
  pill: "BD",
  by: "BD de {name}",
  read: "Lire la BD",
  page: {
    metaSuffix: "BD Origins TCG",
    published: "Publiée le {date}",
    updated: "mise à jour le {date}",
    pagesOne: "1 planche",
    pagesMany: "{n} planches",
    pageAlt: "Planche {n} sur {total}",
    pageAltText: "Planche {n} sur {total}. {text}",
    open: "Ouvrir la planche {n} en taille réelle",
    transcript: "Transcription",
    transcriptIntro: "Le texte de chaque planche, dans l'ordre : pour les lecteurs d'écran et pour qui préfère le lire.",
    noText: "Aucun texte sur cette planche.",
    translatedNote: "Textes traduits automatiquement (version originale en {lang}) : les bulles restent dans la langue d'origine.",
    originalNote: "Les textes sont en {lang} : la traduction sera prête dans quelques minutes.",
    moreTitle: "D'autres BD",
    allComics: "Toutes les BD",
    allNews: "Toutes les actus",
    unavailable: "Les BD ne sont pas encore disponibles : réessayez dans quelques minutes.",
  },
  hub: {
    title: "BD Origins TCG",
    metaTitle: "BD Origins TCG des créateurs de la communauté",
    description: "BD sur Origins TCG dessinées par les créateurs de la communauté OriginsMeta : actus, histoires et vie du jeu, textes traduits dans les langues du site.",
    intro: "Des BD sur Origins TCG dessinées par les créateurs de la communauté : actus, histoires et vie du jeu. Elles paraissent aussi parmi les actus.",
    empty: "Pas encore de BD : la première arrive.",
  },
  cta: {
    title: "Publier une BD",
    text: "En tant que Creator, vous pouvez publier vos BD parmi les actus : planches, couverture et textes, traduits par le site dans les autres langues.",
    button: "Publier une BD",
  },
  newTitle: "Publier une BD",
  newDescription: "Publiez une BD Origins TCG sur OriginsMeta : planches, couverture et textes, parmi les actus, sous votre nom et traduite automatiquement.",
  newIntro: "Planches, couverture et textes : la BD paraît parmi les actus, sous votre nom, avec sa propre page. Le site traduit le titre, la présentation et les textes des planches dans les autres langues.",
  editTitle: "Modifier la BD",
  notAllowed: {
    title: "Les BD sont réservées aux Creators et au Staff",
    text: "Publier des BD parmi les actus est réservé aux rôles Creator et Staff. Si vous dessinez des BD sur Origins TCG, écrivez au staff depuis votre messagerie.",
  },
  editor: {
    lang: "Langue des textes",
    langHint: "La langue des bulles et des textes ci-dessous. Le site traduit le titre, la présentation et les textes des planches dans les autres langues ; si vous avez aussi dessiné la BD dans une autre langue, ajoutez cette version plus bas.",
    title: "Titre",
    summary: "Présentation",
    summaryHint: "2 ou 3 phrases, de {min} à {max} caractères : elles apparaissent dans la liste des actus, sur la page d'accueil et quand le lien est partagé.",
    cover: "Couverture",
    coverHint: "16:9, au moins {minw} × {minh} px (l'idéal est {w} × {h}), PNG, JPG ou WebP : nous la recadrons au centre en 16:9. Elle apparaît dans la liste des actus, sur la page d'accueil et quand le lien est partagé.",
    coverUpload: "Importer la couverture",
    coverReplace: "Changer la couverture",
    coverAlt: "Couverture de la BD",
    uploading: "Envoi en cours…",
    pages: "Planches",
    pagesHint: "Des images verticales à lire de haut en bas : {w} px de large et jusqu'à {h} px de haut (9:16). Une histoire plus longue se répartit sur plusieurs images, jusqu'à {max} ; les cases isolées en 1080 × 1350 (4:5) conviennent aussi. PNG, JPG ou WebP jusqu'à 20 Mo : le site les réduit et les convertit.",
    pagesAdd: "Ajouter des planches",
    pagesUploading: "Envoi de la planche {n} sur {total}…",
    pagesCount: "{n} planches sur {max}",
    pageLabel: "Planche {n}",
    pageText: "Texte de la planche {n}",
    pageTextHint: "Dialogues, cartouches et onomatopées, dans l'ordre de lecture. Facultatif, mais c'est ce que lisent les lecteurs d'écran et Google, et c'est ce que nous traduisons.",
    pageUp: "Monter",
    pageDown: "Descendre",
    pageRemove: "Retirer",
    uploadErrors: {
      type: "Ce fichier n'est pas une image PNG, JPG ou WebP.",
      tooBig: "L'image est encore trop lourde après compression : essayez-en une plus légère.",
      upload: "L'envoi a échoué : vérifiez votre connexion et réessayez.",
      limit: "Vous avez atteint la limite d'images importées : supprimez une BD dont vous n'avez plus besoin, ou écrivez au staff.",
      source: "Ce fichier dépasse 20 Mo : exportez une version plus légère.",
      full: "Une BD compte au plus {max} planches.",
    },
    rights: "Uniquement des dessins qui sont les vôtres ou que vous avez le droit de publier, et aucune carte pas encore annoncée.",
    saveDraft: "Enregistrer le brouillon",
    publish: "Publier",
    update: "Enregistrer les modifications",
    unpublish: "Remettre en brouillon",
    saving: "Enregistrement…",
    saved: "Brouillon enregistré.",
    statusDraft: "Brouillon : vous seul pouvez le voir.",
    statusPublished: "Publiée : chaque modification est en ligne immédiatement.",
    statusHidden: "Masquée par le staff : écrivez au staff depuis votre messagerie pour en connaître la raison.",
    counter: "{n}/{max}",
    consent: "En publiant, la BD est mise en ligne parmi les actus, sous votre nom, avec les traductions automatiques des textes faites par le site, et annoncée sur notre Discord. Vous pouvez la remettre en brouillon ou la supprimer quand vous voulez.",
    editions: {
      title: "Versions dessinées dans d'autres langues",
      hint: "Vous avez aussi dessiné la BD dans une autre langue, avec les bulles réécrites ? Ajoutez cette version ici : ses lecteurs voient ses planches, son titre et sa présentation à la place de la traduction automatique. Cela reste une seule BD, une seule actu, une seule adresse.",
      heading: "Version en {lang}",
      add: "Ajouter la version en {lang}",
      remove: "Retirer la version en {lang}",
      confirmRemove: "Retirer la version en {lang} et ses images ?",
      cover: "Couverture de cette version (facultative)",
      coverHint: "Seulement si la couverture comporte du texte : sans, c'est celle de la BD qui est utilisée.",
    },
  },
  errors: {
    lang: "Choisissez la langue des textes.",
    title: "Titre : de {min} à {max} caractères sur une ligne (un brouillon n'en demande qu'un).",
    summary: "Présentation : de {min} à {max} caractères pour publier (un brouillon peut la laisser vide).",
    pages: "Planches : de 1 à {max} pour publier.",
    page: "Planche {n} : l'image ou son texte ne peut pas être utilisé. Importez-la de nouveau.",
    cover: "Importez une couverture pour publier.",
    notLoggedIn: "Connectez-vous pour publier une BD.",
    forbidden: "Publier des BD est réservé aux Creators et au Staff.",
    disabled: "Les comptes sont désactivés sur cette copie du site.",
    unavailable: "Les BD ne sont pas encore disponibles : réessayez dans quelques minutes.",
    comic_daily_limit: "Vous avez déjà publié 3 nouvelles BD ces dernières 24 heures : enregistrez celle-ci en brouillon et publiez-la demain.",
    comic_limit: "Vous avez atteint 500 BD : supprimez-en une ancienne pour en publier une nouvelle.",
    comic_rate: "Vous avez commencé 10 BD ces dernières 24 heures : réessayez demain.",
    comic_hidden: "Le staff a masqué cette BD : écrivez au staff depuis votre messagerie.",
    comic_hidden_recent: "Le staff a masqué l'une de vos BD ces dernières 24 heures : vous pourrez publier de nouveau demain. En attendant, enregistrez celle-ci en brouillon.",
    comic_status: "Cette modification est réservée au staff.",
    comic_file: "L'une des images est introuvable : importez-la de nouveau.",
    comic_translation: "La traduction n'a pas pu être enregistrée : les textes restent tels quels.",
    comic_reserved_fields: "Cette modification n'est pas autorisée.",
    duplicate: "Un problème est survenu avec l'adresse de la BD : réessayez.",
    db: "L'enregistrement a échoué : réessayez dans un instant.",
    tooFast: "Attendez {n} secondes avant d'enregistrer de nouveau.",
    editions: "Les versions dans d'autres langues ne peuvent pas être utilisées : vérifiez-les et réessayez.",
    edition_title: "Version en {lang}, titre : de {min} à {max} caractères sur une ligne.",
    edition_summary: "Version en {lang}, présentation : de {min} à {max} caractères pour publier.",
    edition_pages: "Version en {lang}, planches : de 1 à {max} pour publier.",
    edition_page: "Version en {lang}, planche {n} : l'image ou son texte ne peut pas être utilisé. Importez-la de nouveau.",
    edition_cover: "Version en {lang} : la couverture ne peut pas être utilisée. Importez-la de nouveau.",
  },
  account: {
    title: "Mes BD",
    intro: "Brouillons, BD publiées et BD masquées par le staff. Seules les BD publiées apparaissent sur le site, parmi les actus.",
    none: "Pas encore de BD.",
    write: "Publier une BD",
    view: "Voir",
    edit: "Modifier",
    status: { draft: "Brouillon", published: "Publiée", hidden: "Masquée par le staff" },
  },
  owner: {
    edit: "Modifier",
    unpublish: "Remettre en brouillon",
    delete: "Supprimer",
    confirmDelete: "Supprimer cette BD et ses images ? Cette action est irréversible.",
    hide: "Masquer (staff)",
    unhide: "Remettre en ligne (staff)",
  },
  profile: {
    title: "BD",
  },
  privacy:
    "BD. Les Creators et le Staff peuvent publier des BD parmi les actus. Les planches et la couverture sont stockées comme les autres images que vous importez sur le site (voir plus haut : votre navigateur les réduit et les réencode, en retirant des données comme la position) ; le titre, la présentation et les textes des planches sont publics sur la page de la BD, avec votre nom et un lien vers votre profil, et le site traduit le titre, la présentation et les textes dans les autres langues avec le même service que pour les guides. Quand une BD paraît, les personnes qui vous suivent reçoivent une notification et notre Discord l'annonce. Vous pouvez modifier une BD, la remettre en brouillon ou la supprimer à tout moment : la supprimer supprime aussi ses images. Le staff peut masquer une BD qui ne respecte pas les règles du site.",
};

export const comicLabels: Record<Locale, ComicLabels> = { en, it, es, fr };

/** Nomi delle lingue nella lingua della pagina, per le note sulla traduzione dei testi ("l'originale è in spagnolo"). */
export const COMIC_LANG_NAMES: Record<Locale, Record<Locale, string>> = {
  en: { en: "English", it: "Italian", es: "Spanish", fr: "French" },
  it: { en: "inglese", it: "italiano", es: "spagnolo", fr: "francese" },
  es: { en: "inglés", it: "italiano", es: "español", fr: "francés" },
  fr: { en: "anglais", it: "italien", es: "espagnol", fr: "français" },
};
