import type { Locale } from "./i18n";

/**
 * Testi delle guide della community (pacchetto GUIDE, 27/09/2026): pagina pubblica /guides/community/[slug], sezione di
 * /guides, riquadro "Scrivi una guida", modulo di scrittura (/guides/new e /edit), pannello in /account, segnalazione.
 * Un modulo solo, nelle tre lingue insieme (`en` è il tipo di riferimento), come `creatorLabels.ts` e `videoLabels.ts`;
 * spagnolo neutro col tú (docs/spagnolo.md). Segnaposto fra graffe ({n}, {min}, {max}, {lang}, {date}, {name}…), riempiti
 * con `fillLabel` di deckQuality.ts (i valori non passano da `replace`, quindi un `$` scritto da un utente resta com'è).
 * I componenti client ricevono dal server solo le etichette della loro lingua (`guideEditorLabels`, `.report`, `.cta`).
 * Nessun import a runtime: il test guides.test.ts lo carica con `node --test`.
 */
const en = {
  /** pagina pubblica */
  page: {
    kicker: "Community guide",
    /** coda del title in SERP ({title} · coda), la toglie `pageTitleWith` se il titolo è lungo */
    metaSuffix: "Origins TCG guide",
    /** description quando il testo non si legge nella lingua della pagina (pagina noindex, traduzione in arrivo) */
    metaFallback: "{title}: an Origins TCG guide by {author}, written in {lang}. On OriginsMeta, the unofficial Origins TCG fan site.",
    by: "by",
    published: "Published {date}",
    updated: "updated {date}",
    readTime: "{n} min read",
    /** guida nella lingua dell'autore: la traduzione automatica non è ancora arrivata */
    langNote: "This guide was written in {lang} by its author and is shown as written: the automatic translation is not ready yet.",
    cardsTitle: "Cards in this guide",
    videoOne: "Video",
    videoMany: "Videos",
    resources: "Resources",
    resourcesNote: "Links chosen by the author of the guide. They lead outside OriginsMeta.",
    moreGuides: "More community guides",
    /** firma in fondo alla guida: di chi è il testo, e che il sito non lo rivede */
    authorNote: "Written and published by {name}. OriginsMeta does not edit community guides: the author is responsible for the text.",
    hiddenNote: "Hidden by the staff: only the author and the staff can see this guide.",
    /** pannello dopo la prima pubblicazione (?new=1, solo per l'autore) */
    newTitle: "Your guide is online",
    newText: "Copy the link and share it: the guide also lands on our Discord, and the site translates it into the other languages of the site within a few minutes.",
  },
  /** sezione "Guide della community" di /guides */
  list: {
    title: "Community guides",
    intro: "Written and published by the site's Authors, Creators and Pro players, and translated automatically into the other languages.",
    by: "by {name}",
    /** link dalla sezione di /guides all'elenco completo */
    all: "All community guides",
  },
  /** pagina /guides/community: tutte le guide della community che si leggono nella lingua della pagina */
  listPage: {
    title: "Community guides",
    metaTitle: "Origins TCG community guides by creators and pros",
    description: "Origins TCG guides written by the Authors, Creators and Pro players of OriginsMeta: decks, ranked, matchups and strategy, kept up to date by their authors.",
    intro: "Every guide written and published by the site's Authors, Creators and Pro players that reads in English, newest first. Guides in other languages appear here as soon as their translation is ready.",
    empty: "No community guide reads in English yet: the first ones will appear here as soon as they are published or translated.",
    count: "{n} guides",
  },
  /** riquadro di /guides per chi ha il ruolo (al posto di "Mandaci la tua guida") */
  cta: {
    title: "Write a guide",
    text: "Your role lets you publish guides on OriginsMeta directly: they go online under your name and the site translates them into the other languages of the site.",
    button: "Write a guide",
  },
  /** /guides/new senza il ruolo */
  notAllowed: {
    title: "Guides are published by the site's roles",
    text: "Authors, Creators, Pro players and Staff publish their guides directly. You can still send us yours: the staff reads it and, if it fits the site, publishes it under your name.",
    button: "Send us your guide",
  },
  newTitle: "Write a guide",
  newDescription: "Write an Origins TCG guide on OriginsMeta: sections, cards, videos and a cover, published under your name and translated automatically.",
  newIntro: "Plain text, in sections: card names become links by themselves. Save a draft whenever you want; when you publish, the guide goes online under your name and the site translates it into the other languages of the site.",
  editTitle: "Edit your guide",
  unavailable: "Community guides are not available yet: try again in a few minutes.",
  editor: {
    title: "Title",
    titleHint: "{min}–{max} characters. The site translates it into the other languages together with the rest of the guide; card names stay in English.",
    titlePlaceholder: "E.g. Dorothy Combo: mulligan, matchups and the turns that matter",
    lang: "Language of the guide",
    langHint: "The site translates the guide into the other languages of the site after you publish it.",
    category: "Category",
    summary: "Summary",
    summaryHint: "{min}–{max} characters: the opening of the guide, also shown in the lists and on Google.",
    summaryPlaceholder: "What the guide explains and who it is for, in two or three sentences.",
    sections: "Sections",
    sectionsHint: "From 1 to 12. Plain text, no formatting: an empty line starts a new paragraph, and card names become links by themselves.",
    sectionN: "Section {n}",
    heading: "Section title",
    headingPlaceholder: "Mulligan, early turns, matchups…",
    body: "Text",
    bodyPlaceholder: "Explain it as you would to a friend at the table.",
    moveUp: "Move section {n} up",
    moveDown: "Move section {n} down",
    remove: "Remove",
    removeSection: "Remove section {n}",
    addSection: "+ Add a section",
    cards: "Cards",
    cardsHint: "Up to {max}: the cards the guide is about, shown in a row under the text.",
    cardSearch: "Search a card",
    cardSearchPlaceholder: "Name of the card",
    cardAdd: "Add {name}",
    cardRemove: "Remove {name}",
    cardNoMatch: "No card with that name.",
    cover: "Cover",
    coverHint: "An image from the official Origins TCG media kit (by Koin Games) or your own image, shown whole at the top of the guide, in the lists and when the link is shared.",
    /** copertina caricata (29/09/2026) */
    coverImage: "Your image",
    coverUpload: "Upload an image",
    coverUploadReplace: "Change the image",
    coverUploading: "Uploading…",
    coverUploadHint: "16:9, at least {minw} × {minh} px ({w} × {h} is ideal), PNG, JPG or WebP up to 2 MB: we crop it to 16:9 from the center. Only images that are yours or that you have the right to use.",
    coverUploadOwner: "Only the author of the guide can upload its cover.",
    coverUploadErrors: {
      type: "This file is not a PNG, JPG or WebP image.",
      tooBig: "The image is too heavy even after compression: try a smaller one.",
      upload: "The upload didn't go through: check your connection and try again.",
      limit: "You have reached the limit of uploaded images: remove the ones you no longer use, or write to the staff.",
    },
    /** nomi delle copertine: le Leggendarie con il nome della carta, in inglese come nel gioco */
    covers: { "keyart-king-arthur": "King Arthur", "keyart-mulan": "Mulan", "keyart-queen-of-hearts": "Queen of Hearts", "keyart-robin-hood": "Robin Hood", "keyart-winnie-the-pooh": "Winnie the Pooh", "keyart-puss-in-boots": "Puss in Boots", "keyart-goldi": "Goldi", "keyart-queen-of-hearts-cyber": "Queen of Hearts (cyber)", "keyart-red-wide": "Red", "hero-1920": "Origins TCG", "ls-two-ways": "Two ways to collect", "ls-zero-pay-to-win": "Zero pay-to-win", "ls-real-collecting": "Real collecting", "ls-collect-them-all": "Collect them all", "ls-collector-pack": "Collector pack" },
    counter: "{n}/{max}",
    preview: "Preview",
    edit: "Write",
    previewNote: "Preview: on the published page card names become links.",
    saveDraft: "Save draft",
    publish: "Publish",
    update: "Save changes",
    unpublish: "Move back to drafts",
    saving: "Saving…",
    saved: "Draft saved.",
    restored: "We restored the text you were writing in this browser.",
    restoreClear: "Start over",
    statusDraft: "Draft: only you can see it.",
    statusPublished: "Published: every change goes online right away.",
    statusHidden: "Hidden by the staff: write to the staff from your messages to know why.",
    meterBelow: "{n} of {min} words. With at least {min} words (summary plus sections) the guide can appear on Google; shorter guides stay on the site only.",
    meterOk: "{n} words: the guide can appear on Google.",
    consent: "Publishing puts the guide online under your name, with the site's automatic translations, and announces it on our Discord. You can move it back to drafts or delete it whenever you want.",
  },
  errors: {
    title: "Title: from {min} to {max} characters on one line (a draft needs just one).",
    summary: "Summary: from {min} to {max} characters to publish (a draft can leave it empty).",
    sections: "Sections: from 1 to 12, each with a title and some text.",
    heading: "Section {n}: the title needs 1 to {max} characters on one line.",
    body: "Section {n}: the text needs 1 to {max} characters.",
    category: "Choose a category.",
    lang: "Choose the language of the guide.",
    cover: "Choose a cover.",
    coverImage: "The uploaded cover can't be found or can't be used: upload it again, or choose a cover from the media kit.",
    cards: "Up to {max} cards.",
    notLoggedIn: "Sign in to write a guide.",
    forbidden: "Publishing guides is for Authors, Creators, Pro players and Staff.",
    disabled: "Accounts are switched off on this copy of the site.",
    unavailable: "Community guides are not available yet: try again in a few minutes.",
    guide_daily_limit: "You have already published 3 new guides in the last 24 hours: save this one as a draft and publish it tomorrow.",
    guide_limit: "You have reached 100 guides: delete an old one to write a new one.",
    guide_rate: "You have started 10 guides in the last 24 hours: try again tomorrow.",
    guide_hidden: "The staff has hidden this guide: write to the staff from your messages.",
    guide_hidden_recent: "The staff hid one of your guides in the last 24 hours: you can publish again tomorrow. Save this one as a draft meanwhile, and write to the staff from your messages if you want to know why.",
    guide_status: "This change is for the staff only.",
    duplicate: "Something went wrong with the address of the guide: try again.",
    db: "Saving failed: try again in a moment.",
    /** {n} = secondi da aspettare */
    tooFast: "You saved this guide a moment ago: wait {n} seconds and save again.",
  },
  /** comandi del proprietario e dello staff sulla pagina pubblica */
  owner: {
    edit: "Edit",
    unpublish: "Move back to drafts",
    delete: "Delete",
    confirmDelete: "Delete this guide for good? It cannot be undone.",
    hide: "Hide (staff)",
    unhide: "Put back online (staff)",
  },
  report: {
    open: "Report this guide",
    reason: "What's wrong with it?",
    placeholder: "Copied text, wrong information, spam…",
    send: "Send the report",
    sending: "Sending…",
    sent: "Thanks: the staff will look into it.",
    login: "Sign in to report this guide",
    cancel: "Cancel",
    errors: {
      reason: "Write at least 3 characters (up to 500).",
      duplicate: "You have already reported this guide: the staff will look into it.",
      report_rate: "You have sent many reports today: try again tomorrow.",
      notLoggedIn: "Sign in to report this guide.",
      own: "You can't report your own guide: to change it, edit it.",
      forbidden: "This guide can't be reported (it may have been hidden or deleted).",
      db: "Sending failed: try again in a moment.",
    },
  },
  account: {
    title: "My guides",
    intro: "Drafts, published guides and guides hidden by the staff. Only published guides appear on the site.",
    none: "No guides yet.",
    write: "Write a guide",
    view: "View",
    edit: "Edit",
    status: { draft: "Draft", published: "Published", hidden: "Hidden by the staff" },
    words: "{n} words",
  },
  /** guide dell'iscritto sulla sua pagina /u */
  profile: {
    title: "Guides",
    /** contatore nella testata di /u, accanto a mazzi e tier list */
    countOne: "guide",
    countMany: "guides",
  },
  /** paragrafo della pagina /privacy, ancora #community-guides */
  privacy:
    "Community guides: the site's Authors, Creators, Pro players and Staff can publish guides under their username. Title, text, language, category, chosen cards, videos and links of a published guide are public; drafts and guides hidden by the staff are visible only to the author and the staff. They are stored on Supabase (servers in Ireland, EU) with the account. After publication the text of the guide (not the title) is sent to Anthropic's API (United States) to be translated into the site's other two languages, and nothing about the author is sent with it; a new guide is also announced, with its title, summary and author name, on the OriginsMeta Discord server (Discord Inc., United States). If you report a guide we keep who reported it, the reason and when, read only by the staff; the first report of a guide in a day also reaches the staff's private Discord channel, with the reason and your username. Your guides and the reports you made are deleted with your account; to delete a guide sooner use \"Delete\" or write to staff@originsmeta.com.",
};

export type CommunityGuideLabels = typeof en;

export const communityGuideLabels: Record<Locale, CommunityGuideLabels> = {
  en,
  it: {
    page: {
      kicker: "Guida della community",
      metaSuffix: "guida di Origins TCG",
      metaFallback: "{title}: una guida di Origins TCG di {author}, scritta in {lang}. Su OriginsMeta, il sito fan non ufficiale di Origins TCG.",
      by: "di",
      published: "Pubblicata il {date}",
      updated: "aggiornata il {date}",
      readTime: "{n} min di lettura",
      langNote: "Questa guida è stata scritta in {lang} dal suo autore e viene mostrata così com'è: la traduzione automatica non è ancora pronta.",
      cardsTitle: "Le carte della guida",
      videoOne: "Video",
      videoMany: "Video",
      resources: "Risorse",
      resourcesNote: "Link scelti dall'autore della guida. Portano fuori da OriginsMeta.",
      moreGuides: "Altre guide della community",
      authorNote: "Scritta e pubblicata da {name}. OriginsMeta non rivede le guide della community: del testo risponde l'autore.",
      hiddenNote: "Nascosta dallo staff: questa guida la vedono solo l'autore e lo staff.",
      newTitle: "La tua guida è online",
      newText: "Copia il link e condividilo: la guida arriva anche sul nostro Discord, e il sito la traduce nelle altre lingue del sito entro pochi minuti.",
    },
    list: {
      title: "Guide della community",
      intro: "Scritte e pubblicate da Autori, Creator e giocatori Pro del sito, e tradotte in automatico nelle altre lingue.",
      by: "di {name}",
      all: "Tutte le guide della community",
    },
    listPage: {
      title: "Guide della community",
      metaTitle: "Guide della community di Origins TCG: creator e pro",
      description: "Guide di Origins TCG scritte da Autori, Creator e giocatori Pro di OriginsMeta: mazzi, classificata, matchup e strategia, aggiornate dai loro autori.",
      intro: "Tutte le guide scritte e pubblicate da Autori, Creator e giocatori Pro del sito che si leggono in italiano, dalla più recente. Le guide scritte in altre lingue arrivano qui appena è pronta la traduzione.",
      empty: "Ancora nessuna guida della community si legge in italiano: le prime compariranno qui appena saranno pubblicate o tradotte.",
      count: "{n} guide",
    },
    cta: {
      title: "Scrivi una guida",
      text: "Il tuo ruolo ti permette di pubblicare guide su OriginsMeta direttamente: vanno online a tuo nome e il sito le traduce nelle altre lingue del sito.",
      button: "Scrivi una guida",
    },
    notAllowed: {
      title: "Le guide le pubblicano i ruoli del sito",
      text: "Autori, Creator, giocatori Pro e Staff pubblicano le loro guide direttamente. Puoi comunque mandarci la tua: lo staff la legge e, se è adatta al sito, la pubblica a tuo nome.",
      button: "Mandaci la tua guida",
    },
    newTitle: "Scrivi una guida",
    newDescription: "Scrivi una guida di Origins TCG su OriginsMeta: sezioni, carte, video e copertina, pubblicata a tuo nome e tradotta in automatico.",
    newIntro: "Testo semplice, a sezioni: i nomi delle carte diventano link da soli. Salva una bozza quando vuoi; quando pubblichi, la guida va online a tuo nome e il sito la traduce nelle altre lingue del sito.",
    editTitle: "Modifica la tua guida",
    unavailable: "Le guide della community non sono ancora disponibili: riprova tra qualche minuto.",
    editor: {
      title: "Titolo",
      titleHint: "{min}–{max} caratteri. Il sito lo traduce nelle altre lingue insieme al resto della guida; i nomi delle carte restano in inglese.",
      titlePlaceholder: "Es. Dorothy Combo: mulligan, matchup e i turni che contano",
      lang: "Lingua della guida",
      langHint: "Il sito traduce la guida nelle altre lingue del sito dopo la pubblicazione.",
      category: "Categoria",
      summary: "Riassunto",
      summaryHint: "{min}–{max} caratteri: l'attacco della guida, che compare anche negli elenchi e su Google.",
      summaryPlaceholder: "Che cosa spiega la guida e a chi serve, in due o tre frasi.",
      sections: "Sezioni",
      sectionsHint: "Da 1 a 12. Testo semplice, senza formattazione: una riga vuota inizia un paragrafo, e i nomi delle carte diventano link da soli.",
      sectionN: "Sezione {n}",
      heading: "Titolo della sezione",
      headingPlaceholder: "Mulligan, primi turni, matchup…",
      body: "Testo",
      bodyPlaceholder: "Spiegalo come lo spiegheresti a un amico al tavolo.",
      moveUp: "Sposta su la sezione {n}",
      moveDown: "Sposta giù la sezione {n}",
      remove: "Togli",
      removeSection: "Togli la sezione {n}",
      addSection: "+ Aggiungi una sezione",
      cards: "Carte",
      cardsHint: "Fino a {max}: le carte di cui parla la guida, mostrate in fila sotto il testo.",
      cardSearch: "Cerca una carta",
      cardSearchPlaceholder: "Nome della carta",
      cardAdd: "Aggiungi {name}",
      cardRemove: "Togli {name}",
      cardNoMatch: "Nessuna carta con questo nome.",
      cover: "Copertina",
      coverHint: "Un'immagine del media kit ufficiale di Origins TCG (di Koin Games) oppure una tua, mostrata intera in testa alla guida, negli elenchi e quando si condivide il link.",
      coverImage: "La tua immagine",
      coverUpload: "Carica un'immagine",
      coverUploadReplace: "Cambia l'immagine",
      coverUploading: "Caricamento…",
      coverUploadHint: "16:9, almeno {minw} × {minh} px (l'ideale è {w} × {h}), PNG, JPG o WebP fino a 2 MB: la ritagliamo al centro in 16:9. Solo immagini tue o che hai il diritto di usare.",
      coverUploadOwner: "Solo l'autore della guida può caricarne la copertina.",
      coverUploadErrors: {
        type: "Il file non è un'immagine PNG, JPG o WebP.",
        tooBig: "L'immagine è troppo pesante anche dopo la compressione: provane una più piccola.",
        upload: "Il caricamento non è riuscito: controlla la connessione e riprova.",
        limit: "Hai raggiunto il tetto delle immagini caricate: togli quelle che non usi più, oppure scrivi allo staff.",
      },
      covers: { "keyart-king-arthur": "King Arthur", "keyart-mulan": "Mulan", "keyart-queen-of-hearts": "Queen of Hearts", "keyart-robin-hood": "Robin Hood", "keyart-winnie-the-pooh": "Winnie the Pooh", "keyart-puss-in-boots": "Puss in Boots", "keyart-goldi": "Goldi", "keyart-queen-of-hearts-cyber": "Queen of Hearts (cyber)", "keyart-red-wide": "Red", "hero-1920": "Origins TCG", "ls-two-ways": "Due modi di collezionare", "ls-zero-pay-to-win": "Zero pay-to-win", "ls-real-collecting": "Collezionismo vero", "ls-collect-them-all": "Collezionale tutte", "ls-collector-pack": "Bustina da collezione" },
      counter: "{n}/{max}",
      preview: "Anteprima",
      edit: "Scrivi",
      previewNote: "Anteprima: nella pagina pubblicata i nomi delle carte diventano link.",
      saveDraft: "Salva bozza",
      publish: "Pubblica",
      update: "Salva le modifiche",
      unpublish: "Riporta tra le bozze",
      saving: "Salvataggio…",
      saved: "Bozza salvata.",
      restored: "Abbiamo ripreso il testo che stavi scrivendo in questo browser.",
      restoreClear: "Ricomincia da capo",
      statusDraft: "Bozza: la vedi solo tu.",
      statusPublished: "Pubblicata: ogni modifica va subito online.",
      statusHidden: "Nascosta dallo staff: scrivi allo staff dai tuoi messaggi per sapere perché.",
      meterBelow: "{n} parole su {min}. Con almeno {min} parole (riassunto più sezioni) la guida può comparire su Google; con meno resta solo sul sito.",
      meterOk: "{n} parole: la guida può comparire su Google.",
      consent: "Pubblicando, la guida va online a tuo nome con le traduzioni automatiche del sito e viene annunciata sul nostro Discord. Puoi riportarla tra le bozze o eliminarla quando vuoi.",
    },
    errors: {
      title: "Titolo: da {min} a {max} caratteri su una riga (a una bozza ne basta uno).",
      summary: "Riassunto: da {min} a {max} caratteri per pubblicare (in una bozza può restare vuoto).",
      sections: "Sezioni: da 1 a 12, ognuna con un titolo e un testo.",
      heading: "Sezione {n}: il titolo vuole da 1 a {max} caratteri su una riga.",
      body: "Sezione {n}: il testo vuole da 1 a {max} caratteri.",
      category: "Scegli una categoria.",
      lang: "Scegli la lingua della guida.",
      cover: "Scegli una copertina.",
      coverImage: "La copertina caricata non si trova o non si può usare: caricala di nuovo, oppure scegline una del media kit.",
      cards: "Al massimo {max} carte.",
      notLoggedIn: "Accedi per scrivere una guida.",
      forbidden: "La pubblicazione delle guide è per Autori, Creator, giocatori Pro e Staff.",
      disabled: "Gli account sono spenti in questa copia del sito.",
      unavailable: "Le guide della community non sono ancora disponibili: riprova tra qualche minuto.",
      guide_daily_limit: "Hai già pubblicato 3 guide nuove nelle ultime 24 ore: salva questa come bozza e pubblicala domani.",
      guide_limit: "Hai raggiunto 100 guide: eliminane una vecchia per scriverne una nuova.",
      guide_rate: "Hai iniziato 10 guide nelle ultime 24 ore: riprova domani.",
      guide_hidden: "Lo staff ha nascosto questa guida: scrivi allo staff dai tuoi messaggi.",
      guide_hidden_recent: "Nelle ultime 24 ore lo staff ha nascosto una tua guida: potrai pubblicare di nuovo domani. Intanto salva questa come bozza; se vuoi sapere perché, scrivi allo staff dai tuoi messaggi.",
      guide_status: "Questa modifica è riservata allo staff.",
      duplicate: "Qualcosa è andato storto con l'indirizzo della guida: riprova.",
      db: "Salvataggio non riuscito: riprova tra un momento.",
      tooFast: "Hai salvato questa guida un attimo fa: aspetta {n} secondi e salva di nuovo.",
    },
    owner: {
      edit: "Modifica",
      unpublish: "Riporta tra le bozze",
      delete: "Elimina",
      confirmDelete: "Eliminare questa guida per sempre? Non si può annullare.",
      hide: "Nascondi (staff)",
      unhide: "Rimetti online (staff)",
    },
    report: {
      open: "Segnala questa guida",
      reason: "Che cosa non va?",
      placeholder: "Testo copiato, informazioni sbagliate, spam…",
      send: "Manda la segnalazione",
      sending: "Invio…",
      sent: "Grazie: lo staff ci darà un'occhiata.",
      login: "Accedi per segnalare questa guida",
      cancel: "Annulla",
      errors: {
        reason: "Scrivi almeno 3 caratteri (fino a 500).",
        duplicate: "Hai già segnalato questa guida: lo staff ci darà un'occhiata.",
        report_rate: "Oggi hai mandato molte segnalazioni: riprova domani.",
        notLoggedIn: "Accedi per segnalare questa guida.",
        own: "Non puoi segnalare la tua guida: se vuoi cambiarla, modificala.",
        forbidden: "Questa guida non si può segnalare (forse è stata nascosta o eliminata).",
        db: "Invio non riuscito: riprova tra un momento.",
      },
    },
    account: {
      title: "Le mie guide",
      intro: "Bozze, guide pubblicate e guide nascoste dallo staff. Sul sito compaiono solo quelle pubblicate.",
      none: "Ancora nessuna guida.",
      write: "Scrivi una guida",
      view: "Apri",
      edit: "Modifica",
      status: { draft: "Bozza", published: "Pubblicata", hidden: "Nascosta dallo staff" },
      words: "{n} parole",
    },
    profile: {
      title: "Guide",
      countOne: "guida",
      countMany: "guide",
    },
    privacy:
      "Guide della community: Autori, Creator, giocatori Pro e Staff del sito possono pubblicare guide con il loro nome utente. Titolo, testo, lingua, categoria, carte scelte, video e link di una guida pubblicata sono pubblici; le bozze e le guide nascoste dallo staff le vedono solo l'autore e lo staff. Sono conservate su Supabase (server in Irlanda, UE) con l'account. Dopo la pubblicazione il testo della guida (non il titolo) viene inviato all'API di Anthropic (Stati Uniti) per tradurlo nelle altre lingue del sito del sito, senza nessun dato dell'autore; una guida nuova viene anche annunciata, con titolo, riassunto e nome dell'autore, sul server Discord di OriginsMeta (Discord Inc., Stati Uniti). Se segnali una guida conserviamo chi l'ha segnalata, il motivo e quando, e li legge solo lo staff; la prima segnalazione di una guida in una giornata arriva anche al canale Discord privato dello staff, con il motivo e il tuo nome utente. Le tue guide e le segnalazioni che hai fatto si cancellano con l'account; per eliminare prima una guida usa “Elimina” o scrivi a staff@originsmeta.com.",
  },
  es: {
    page: {
      kicker: "Guía de la comunidad",
      metaSuffix: "guía de Origins TCG",
      metaFallback: "{title}: una guía de Origins TCG de {author}, escrita en {lang}. En OriginsMeta, el sitio fan no oficial de Origins TCG.",
      by: "de",
      published: "Publicada el {date}",
      updated: "actualizada el {date}",
      readTime: "{n} min de lectura",
      langNote: "Su autor escribió esta guía en {lang} y la mostramos tal cual: la traducción automática aún no está lista.",
      cardsTitle: "Las cartas de la guía",
      videoOne: "Video",
      videoMany: "Videos",
      resources: "Recursos",
      resourcesNote: "Enlaces elegidos por el autor de la guía. Llevan fuera de OriginsMeta.",
      moreGuides: "Más guías de la comunidad",
      authorNote: "Escrita y publicada por {name}. OriginsMeta no revisa las guías de la comunidad: el autor responde por el texto.",
      hiddenNote: "Oculta por el staff: solo el autor y el staff pueden ver esta guía.",
      newTitle: "Tu guía ya está en línea",
      newText: "Copia el enlace y compártelo: la guía también llega a nuestro Discord, y el sitio la traduce a los otros idiomas del sitio en unos minutos.",
    },
    list: {
      title: "Guías de la comunidad",
      intro: "Escritas y publicadas por los Autores, Creators y jugadores Pro del sitio, y traducidas automáticamente a los otros idiomas.",
      by: "de {name}",
      all: "Todas las guías de la comunidad",
    },
    listPage: {
      title: "Guías de la comunidad",
      metaTitle: "Guías de la comunidad de Origins TCG: creators y pros",
      description: "Guías de Origins TCG escritas por los Autores, Creators y jugadores Pro de OriginsMeta: mazos, clasificatoria, matchups y estrategia, al día.",
      intro: "Todas las guías escritas y publicadas por los Autores, Creators y jugadores Pro del sitio que se leen en español, de la más reciente a la más antigua. Las guías escritas en otros idiomas llegan aquí en cuanto su traducción está lista.",
      empty: "Todavía ninguna guía de la comunidad se lee en español: las primeras aparecerán aquí en cuanto se publiquen o se traduzcan.",
      count: "{n} guías",
    },
    cta: {
      title: "Escribe una guía",
      text: "Tu rol te permite publicar guías en OriginsMeta directamente: salen con tu nombre y se traducen solas a los otros idiomas del sitio.",
      button: "Escribe una guía",
    },
    notAllowed: {
      title: "Las guías las publican los roles del sitio",
      text: "Los Autores, Creators, jugadores Pro y el Staff publican sus guías directamente. Igual puedes enviarnos la tuya: el staff la lee y, si encaja en el sitio, la publica con tu nombre.",
      button: "Envíanos tu guía",
    },
    newTitle: "Escribe una guía",
    newDescription: "Escribe una guía de Origins TCG en OriginsMeta: secciones, cartas, videos y portada, publicada con tu nombre y traducida automáticamente.",
    newIntro: "Texto simple, por secciones: los nombres de las cartas se convierten en enlaces solos. Guarda un borrador cuando quieras; al publicar, la guía sale con tu nombre y el sitio la traduce a los otros idiomas del sitio.",
    editTitle: "Edita tu guía",
    unavailable: "Las guías de la comunidad todavía no están disponibles: vuelve a intentarlo en unos minutos.",
    editor: {
      title: "Título",
      titleHint: "De {min} a {max} caracteres. El sitio lo traduce a los otros idiomas junto con el resto de la guía; los nombres de las cartas se quedan en inglés.",
      titlePlaceholder: "Ej.: Dorothy Combo: mulligan, matchups y los turnos que importan",
      lang: "Idioma de la guía",
      langHint: "El sitio traduce la guía a los otros idiomas del sitio después de publicarla.",
      category: "Categoría",
      summary: "Resumen",
      summaryHint: "De {min} a {max} caracteres: el comienzo de la guía, que también aparece en las listas y en Google.",
      summaryPlaceholder: "Qué explica la guía y para quién es, en dos o tres frases.",
      sections: "Secciones",
      sectionsHint: "De 1 a 12. Texto simple, sin formato: una línea vacía empieza un párrafo, y los nombres de las cartas se convierten en enlaces solos.",
      sectionN: "Sección {n}",
      heading: "Título de la sección",
      headingPlaceholder: "Mulligan, primeros turnos, matchups…",
      body: "Texto",
      bodyPlaceholder: "Explícalo como se lo explicarías a un amigo en la mesa.",
      moveUp: "Subir la sección {n}",
      moveDown: "Bajar la sección {n}",
      remove: "Quitar",
      removeSection: "Quitar la sección {n}",
      addSection: "+ Añadir una sección",
      cards: "Cartas",
      cardsHint: "Hasta {max}: las cartas de las que habla la guía, en una fila debajo del texto.",
      cardSearch: "Busca una carta",
      cardSearchPlaceholder: "Nombre de la carta",
      cardAdd: "Añadir {name}",
      cardRemove: "Quitar {name}",
      cardNoMatch: "Ninguna carta con ese nombre.",
      cover: "Portada",
      coverHint: "Una imagen del media kit oficial de Origins TCG (de Koin Games) o una tuya, mostrada entera al comienzo de la guía, en las listas y al compartir el enlace.",
      coverImage: "Tu imagen",
      coverUpload: "Sube una imagen",
      coverUploadReplace: "Cambia la imagen",
      coverUploading: "Subiendo…",
      coverUploadHint: "16:9, al menos {minw} × {minh} px (lo ideal es {w} × {h}), PNG, JPG o WebP de hasta 2 MB: la recortamos al centro en 16:9. Solo imágenes tuyas o que tengas derecho a usar.",
      coverUploadOwner: "Solo el autor de la guía puede subir su portada.",
      coverUploadErrors: {
        type: "El archivo no es una imagen PNG, JPG o WebP.",
        tooBig: "La imagen pesa demasiado incluso comprimida: prueba con una más pequeña.",
        upload: "No se pudo subir: comprueba la conexión e inténtalo de nuevo.",
        limit: "Has llegado al límite de imágenes subidas: quita las que ya no uses o escribe al staff.",
      },
      covers: { "keyart-king-arthur": "King Arthur", "keyart-mulan": "Mulan", "keyart-queen-of-hearts": "Queen of Hearts", "keyart-robin-hood": "Robin Hood", "keyart-winnie-the-pooh": "Winnie the Pooh", "keyart-puss-in-boots": "Puss in Boots", "keyart-goldi": "Goldi", "keyart-queen-of-hearts-cyber": "Queen of Hearts (cyber)", "keyart-red-wide": "Red", "hero-1920": "Origins TCG", "ls-two-ways": "Dos formas de coleccionar", "ls-zero-pay-to-win": "Cero pay-to-win", "ls-real-collecting": "Coleccionismo de verdad", "ls-collect-them-all": "Colecciónalas todas", "ls-collector-pack": "Sobre de coleccionista" },
      counter: "{n}/{max}",
      preview: "Vista previa",
      edit: "Escribir",
      previewNote: "Vista previa: en la página publicada los nombres de las cartas se convierten en enlaces.",
      saveDraft: "Guardar borrador",
      publish: "Publicar",
      update: "Guardar los cambios",
      unpublish: "Volver a borradores",
      saving: "Guardando…",
      saved: "Borrador guardado.",
      restored: "Recuperamos el texto que estabas escribiendo en este navegador.",
      restoreClear: "Empezar de cero",
      statusDraft: "Borrador: solo lo ves tú.",
      statusPublished: "Publicada: cada cambio sale enseguida.",
      statusHidden: "Oculta por el staff: escribe al staff desde tus mensajes para saber por qué.",
      meterBelow: "{n} de {min} palabras. Con al menos {min} palabras (resumen más secciones), la guía puede aparecer en Google; con menos, se queda solo en el sitio.",
      meterOk: "{n} palabras: la guía puede aparecer en Google.",
      consent: "Al publicar, la guía sale con tu nombre y las traducciones automáticas del sitio, y se anuncia en nuestro Discord. Puedes volver a ponerla en borradores o eliminarla cuando quieras.",
    },
    errors: {
      title: "Título: de {min} a {max} caracteres en una línea (a un borrador le basta uno).",
      summary: "Resumen: de {min} a {max} caracteres para publicar (en un borrador puede quedar vacío).",
      sections: "Secciones: de 1 a 12, cada una con un título y un texto.",
      heading: "Sección {n}: el título necesita de 1 a {max} caracteres en una línea.",
      body: "Sección {n}: el texto necesita de 1 a {max} caracteres.",
      category: "Elige una categoría.",
      lang: "Elige el idioma de la guía.",
      cover: "Elige una portada.",
      coverImage: "La portada subida no se encuentra o no se puede usar: súbela de nuevo, o elige una del media kit.",
      cards: "Hasta {max} cartas.",
      notLoggedIn: "Inicia sesión para escribir una guía.",
      forbidden: "La publicación de guías es para Autores, Creators, jugadores Pro y Staff.",
      disabled: "Las cuentas están desactivadas en esta copia del sitio.",
      unavailable: "Las guías de la comunidad todavía no están disponibles: vuelve a intentarlo en unos minutos.",
      guide_daily_limit: "Ya publicaste 3 guías nuevas en las últimas 24 horas: guarda esta como borrador y publícala mañana.",
      guide_limit: "Llegaste a 100 guías: elimina una antigua para escribir una nueva.",
      guide_rate: "Empezaste 10 guías en las últimas 24 horas: vuelve a intentarlo mañana.",
      guide_hidden: "El staff ocultó esta guía: escribe al staff desde tus mensajes.",
      guide_hidden_recent: "En las últimas 24 horas el staff ocultó una de tus guías: podrás volver a publicar mañana. Mientras tanto, guarda esta como borrador; si quieres saber por qué, escribe al staff desde tus mensajes.",
      guide_status: "Este cambio es solo para el staff.",
      duplicate: "Algo falló con la dirección de la guía: vuelve a intentarlo.",
      db: "No se pudo guardar: vuelve a intentarlo en un momento.",
      tooFast: "Guardaste esta guía hace un momento: espera {n} segundos y vuelve a guardar.",
    },
    owner: {
      edit: "Editar",
      unpublish: "Volver a borradores",
      delete: "Eliminar",
      confirmDelete: "¿Eliminar esta guía para siempre? No se puede deshacer.",
      hide: "Ocultar (staff)",
      unhide: "Volver a publicar (staff)",
    },
    report: {
      open: "Reportar esta guía",
      reason: "¿Qué tiene de malo?",
      placeholder: "Texto copiado, información incorrecta, spam…",
      send: "Enviar el reporte",
      sending: "Enviando…",
      sent: "Gracias: el staff lo revisará.",
      login: "Inicia sesión para reportar esta guía",
      cancel: "Cancelar",
      errors: {
        reason: "Escribe al menos 3 caracteres (hasta 500).",
        duplicate: "Ya reportaste esta guía: el staff la revisará.",
        report_rate: "Hoy enviaste muchos reportes: vuelve a intentarlo mañana.",
        notLoggedIn: "Inicia sesión para reportar esta guía.",
        own: "No puedes reportar tu propia guía: si quieres cambiarla, edítala.",
        forbidden: "Esta guía no se puede reportar (quizá la ocultaron o la eliminaron).",
        db: "No se pudo enviar: vuelve a intentarlo en un momento.",
      },
    },
    account: {
      title: "Mis guías",
      intro: "Borradores, guías publicadas y guías ocultas por el staff. En el sitio solo aparecen las publicadas.",
      none: "Todavía no hay guías.",
      write: "Escribe una guía",
      view: "Ver",
      edit: "Editar",
      status: { draft: "Borrador", published: "Publicada", hidden: "Oculta por el staff" },
      words: "{n} palabras",
    },
    profile: {
      title: "Guías",
      countOne: "guía",
      countMany: "guías",
    },
    privacy:
      "Guías de la comunidad: los Autores, Creators, jugadores Pro y el Staff del sitio pueden publicar guías con su nombre de usuario. El título, el texto, el idioma, la categoría, las cartas elegidas, los videos y los enlaces de una guía publicada son públicos; los borradores y las guías ocultas por el staff solo los ven el autor y el staff. Se guardan en Supabase (servidores en Irlanda, UE) junto con la cuenta. Después de publicarla, el texto de la guía (no el título) se envía a la API de Anthropic (Estados Unidos) para traducirlo a los otros idiomas del sitio, sin ningún dato del autor; una guía nueva también se anuncia, con su título, su resumen y el nombre del autor, en el servidor de Discord de OriginsMeta (Discord Inc., Estados Unidos). Si reportas una guía, guardamos quién la reportó, el motivo y cuándo, y solo los lee el staff; el primer reporte de una guía en un día también llega al canal privado de Discord del staff, con el motivo y tu nombre de usuario. Tus guías y los reportes que hiciste se eliminan con tu cuenta; para eliminar antes una guía usa “Eliminar” o escribe a staff@originsmeta.com.",
  },
  /** Francese (07/10/2026, docs/francese.md): "vous", ruoli Auteur / Creator / Pro / Staff; spazio insecabile prima di : ; ? ! */
  fr: {
    page: {
      kicker: "Guide de la communauté",
      metaSuffix: "guide Origins TCG",
      metaFallback: "{title} : un guide Origins TCG de {author}, écrit en {lang}. Sur OriginsMeta, le site de fans non officiel d'Origins TCG.",
      by: "par",
      published: "Publié le {date}",
      updated: "mis à jour le {date}",
      readTime: "{n} min de lecture",
      langNote: "Ce guide a été écrit en {lang} par son auteur et il est affiché tel quel : la traduction automatique n'est pas encore prête.",
      cardsTitle: "Les cartes du guide",
      videoOne: "Vidéo",
      videoMany: "Vidéos",
      resources: "Ressources",
      resourcesNote: "Liens choisis par l'auteur du guide. Ils mènent hors d'OriginsMeta.",
      moreGuides: "D'autres guides de la communauté",
      authorNote: "Écrit et publié par {name}. OriginsMeta ne relit pas les guides de la communauté : l'auteur est responsable du texte.",
      hiddenNote: "Masqué par le staff : seuls l'auteur et le staff peuvent voir ce guide.",
      newTitle: "Votre guide est en ligne",
      newText: "Copiez le lien et partagez-le : le guide arrive aussi sur notre Discord, et le site le traduit dans les autres langues en quelques minutes.",
    },
    list: {
      title: "Guides de la communauté",
      intro: "Écrits et publiés par les Auteurs, Creators et joueurs Pro du site, et traduits automatiquement dans les autres langues.",
      by: "par {name}",
      all: "Tous les guides de la communauté",
    },
    listPage: {
      title: "Guides de la communauté",
      metaTitle: "Guides Origins TCG de la communauté : créateurs et pros",
      description: "Guides Origins TCG écrits par les Auteurs, Creators et joueurs Pro d'OriginsMeta : decks, classé, matchups et stratégie, tenus à jour par leurs auteurs.",
      intro: "Tous les guides écrits et publiés par les Auteurs, Creators et joueurs Pro du site qui se lisent en français, du plus récent au plus ancien. Les guides écrits dans d'autres langues arrivent ici dès que leur traduction est prête.",
      empty: "Aucun guide de la communauté ne se lit encore en français : les premiers apparaîtront ici dès qu'ils seront publiés ou traduits.",
      count: "{n} guides",
    },
    cta: {
      title: "Écrire un guide",
      text: "Votre rôle vous permet de publier des guides directement sur OriginsMeta : ils sont mis en ligne sous votre nom et le site les traduit dans ses autres langues.",
      button: "Écrire un guide",
    },
    notAllowed: {
      title: "Les guides sont publiés par les rôles du site",
      text: "Les Auteurs, Creators, joueurs Pro et le Staff publient leurs guides directement. Vous pouvez quand même nous envoyer le vôtre : le staff le lit et, s'il convient au site, le publie sous votre nom.",
      button: "Envoyez-nous votre guide",
    },
    newTitle: "Écrire un guide",
    newDescription: "Écrivez un guide Origins TCG sur OriginsMeta : sections, cartes, vidéos et couverture, publié sous votre nom et traduit automatiquement.",
    newIntro: "Du texte simple, en sections : les noms des cartes deviennent des liens tout seuls. Enregistrez un brouillon quand vous voulez ; quand vous publiez, le guide est mis en ligne sous votre nom et le site le traduit dans les autres langues.",
    editTitle: "Modifier votre guide",
    unavailable: "Les guides de la communauté ne sont pas encore disponibles : réessayez dans quelques minutes.",
    editor: {
      title: "Titre",
      titleHint: "{min}–{max} caractères. Le site le traduit dans les autres langues avec le reste du guide ; les noms des cartes restent en anglais.",
      titlePlaceholder: "Ex. Dorothy Combo : mulligan, matchups et les tours qui comptent",
      lang: "Langue du guide",
      langHint: "Le site traduit le guide dans les autres langues après la publication.",
      category: "Catégorie",
      summary: "Résumé",
      summaryHint: "{min}–{max} caractères : l'accroche du guide, affichée aussi dans les listes et sur Google.",
      summaryPlaceholder: "Ce que le guide explique et à qui il s'adresse, en deux ou trois phrases.",
      sections: "Sections",
      sectionsHint: "De 1 à 12. Du texte simple, sans mise en forme : une ligne vide commence un nouveau paragraphe, et les noms des cartes deviennent des liens tout seuls.",
      sectionN: "Section {n}",
      heading: "Titre de la section",
      headingPlaceholder: "Mulligan, premiers tours, matchups…",
      body: "Texte",
      bodyPlaceholder: "Expliquez-le comme à un ami autour de la table.",
      moveUp: "Monter la section {n}",
      moveDown: "Descendre la section {n}",
      remove: "Retirer",
      removeSection: "Retirer la section {n}",
      addSection: "+ Ajouter une section",
      cards: "Cartes",
      cardsHint: "Jusqu'à {max} : les cartes dont parle le guide, affichées en ligne sous le texte.",
      cardSearch: "Rechercher une carte",
      cardSearchPlaceholder: "Nom de la carte",
      cardAdd: "Ajouter {name}",
      cardRemove: "Retirer {name}",
      cardNoMatch: "Aucune carte de ce nom.",
      cover: "Couverture",
      coverHint: "Une image du media kit officiel d'Origins TCG (de Koin Games) ou l'une des vôtres, affichée en entier en tête du guide, dans les listes et quand le lien est partagé.",
      coverImage: "Votre image",
      coverUpload: "Importer une image",
      coverUploadReplace: "Changer l'image",
      coverUploading: "Envoi en cours…",
      coverUploadHint: "16:9, au moins {minw} × {minh} px (l'idéal est {w} × {h}), PNG, JPG ou WebP jusqu'à 2 Mo : nous la recadrons au centre en 16:9. Uniquement des images qui sont les vôtres ou que vous avez le droit d'utiliser.",
      coverUploadOwner: "Seul l'auteur du guide peut importer sa couverture.",
      coverUploadErrors: {
        type: "Ce fichier n'est pas une image PNG, JPG ou WebP.",
        tooBig: "L'image est encore trop lourde après compression : essayez-en une plus petite.",
        upload: "L'envoi a échoué : vérifiez votre connexion et réessayez.",
        limit: "Vous avez atteint la limite d'images importées : retirez celles que vous n'utilisez plus, ou écrivez au staff.",
      },
      covers: { "keyart-king-arthur": "King Arthur", "keyart-mulan": "Mulan", "keyart-queen-of-hearts": "Queen of Hearts", "keyart-robin-hood": "Robin Hood", "keyart-winnie-the-pooh": "Winnie the Pooh", "keyart-puss-in-boots": "Puss in Boots", "keyart-goldi": "Goldi", "keyart-queen-of-hearts-cyber": "Queen of Hearts (cyber)", "keyart-red-wide": "Red", "hero-1920": "Origins TCG", "ls-two-ways": "Deux façons de collectionner", "ls-zero-pay-to-win": "Zéro pay-to-win", "ls-real-collecting": "Une vraie collection", "ls-collect-them-all": "Collectionnez-les toutes", "ls-collector-pack": "Booster collector" },
      counter: "{n}/{max}",
      preview: "Aperçu",
      edit: "Écrire",
      previewNote: "Aperçu : sur la page publiée, les noms des cartes deviennent des liens.",
      saveDraft: "Enregistrer le brouillon",
      publish: "Publier",
      update: "Enregistrer les modifications",
      unpublish: "Remettre en brouillon",
      saving: "Enregistrement…",
      saved: "Brouillon enregistré.",
      restored: "Nous avons récupéré le texte que vous écriviez dans ce navigateur.",
      restoreClear: "Repartir de zéro",
      statusDraft: "Brouillon : vous seul pouvez le voir.",
      statusPublished: "Publié : chaque modification est en ligne immédiatement.",
      statusHidden: "Masqué par le staff : écrivez au staff depuis votre messagerie pour en connaître la raison.",
      meterBelow: "{n} mots sur {min}. Avec au moins {min} mots (résumé plus sections), le guide peut apparaître sur Google ; en dessous, il reste sur le site seulement.",
      meterOk: "{n} mots : le guide peut apparaître sur Google.",
      consent: "En publiant, le guide est mis en ligne sous votre nom, avec les traductions automatiques du site, et annoncé sur notre Discord. Vous pouvez le remettre en brouillon ou le supprimer quand vous voulez.",
    },
    errors: {
      title: "Titre : de {min} à {max} caractères sur une ligne (un brouillon n'en demande qu'un).",
      summary: "Résumé : de {min} à {max} caractères pour publier (un brouillon peut le laisser vide).",
      sections: "Sections : de 1 à 12, chacune avec un titre et du texte.",
      heading: "Section {n} : le titre demande de 1 à {max} caractères sur une ligne.",
      body: "Section {n} : le texte demande de 1 à {max} caractères.",
      category: "Choisissez une catégorie.",
      lang: "Choisissez la langue du guide.",
      cover: "Choisissez une couverture.",
      coverImage: "La couverture importée est introuvable ou ne peut pas être utilisée : importez-la de nouveau, ou choisissez une couverture du media kit.",
      cards: "Au plus {max} cartes.",
      notLoggedIn: "Connectez-vous pour écrire un guide.",
      forbidden: "La publication de guides est réservée aux Auteurs, Creators, joueurs Pro et au Staff.",
      disabled: "Les comptes sont désactivés sur cette copie du site.",
      unavailable: "Les guides de la communauté ne sont pas encore disponibles : réessayez dans quelques minutes.",
      guide_daily_limit: "Vous avez déjà publié 3 nouveaux guides ces dernières 24 heures : enregistrez celui-ci en brouillon et publiez-le demain.",
      guide_limit: "Vous avez atteint 100 guides : supprimez-en un ancien pour en écrire un nouveau.",
      guide_rate: "Vous avez commencé 10 guides ces dernières 24 heures : réessayez demain.",
      guide_hidden: "Le staff a masqué ce guide : écrivez au staff depuis votre messagerie.",
      guide_hidden_recent: "Le staff a masqué l'un de vos guides ces dernières 24 heures : vous pourrez publier de nouveau demain. En attendant, enregistrez celui-ci en brouillon et, pour en connaître la raison, écrivez au staff depuis votre messagerie.",
      guide_status: "Cette modification est réservée au staff.",
      duplicate: "Un problème est survenu avec l'adresse du guide : réessayez.",
      db: "L'enregistrement a échoué : réessayez dans un instant.",
      tooFast: "Vous avez enregistré ce guide il y a un instant : attendez {n} secondes et enregistrez de nouveau.",
    },
    owner: {
      edit: "Modifier",
      unpublish: "Remettre en brouillon",
      delete: "Supprimer",
      confirmDelete: "Supprimer définitivement ce guide ? Cette action est irréversible.",
      hide: "Masquer (staff)",
      unhide: "Remettre en ligne (staff)",
    },
    report: {
      open: "Signaler ce guide",
      reason: "Qu'est-ce qui ne va pas ?",
      placeholder: "Texte copié, informations erronées, spam…",
      send: "Envoyer le signalement",
      sending: "Envoi…",
      sent: "Merci : le staff va y jeter un œil.",
      login: "Connectez-vous pour signaler ce guide",
      cancel: "Annuler",
      errors: {
        reason: "Écrivez au moins 3 caractères (jusqu'à 500).",
        duplicate: "Vous avez déjà signalé ce guide : le staff va y jeter un œil.",
        report_rate: "Vous avez envoyé beaucoup de signalements aujourd'hui : réessayez demain.",
        notLoggedIn: "Connectez-vous pour signaler ce guide.",
        own: "Vous ne pouvez pas signaler votre propre guide : pour le changer, modifiez-le.",
        forbidden: "Ce guide ne peut pas être signalé (il a peut-être été masqué ou supprimé).",
        db: "L'envoi a échoué : réessayez dans un instant.",
      },
    },
    account: {
      title: "Mes guides",
      intro: "Brouillons, guides publiés et guides masqués par le staff. Seuls les guides publiés apparaissent sur le site.",
      none: "Pas encore de guide.",
      write: "Écrire un guide",
      view: "Voir",
      edit: "Modifier",
      status: { draft: "Brouillon", published: "Publié", hidden: "Masqué par le staff" },
      words: "{n} mots",
    },
    profile: {
      title: "Guides",
      countOne: "guide",
      countMany: "guides",
    },
    privacy:
      "Guides de la communauté : les Auteurs, Creators, joueurs Pro et le Staff du site peuvent publier des guides sous leur nom d'utilisateur. Le titre, le texte, la langue, la catégorie, les cartes choisies, les vidéos et les liens d'un guide publié sont publics ; les brouillons et les guides masqués par le staff ne sont visibles que par l'auteur et le staff. Ils sont stockés sur Supabase (serveurs en Irlande, UE) avec le compte. Après la publication, le texte du guide (pas le titre) est envoyé à l'API d'Anthropic (États-Unis) pour être traduit dans les autres langues du site, sans aucune donnée sur l'auteur ; un nouveau guide est aussi annoncé, avec son titre, son résumé et le nom de l'auteur, sur le serveur Discord d'OriginsMeta (Discord Inc., États-Unis). Si vous signalez un guide, nous conservons qui l'a signalé, la raison et la date, lus seulement par le staff ; le premier signalement d'un guide dans la journée arrive aussi sur le canal Discord privé du staff, avec la raison et votre nom d'utilisateur. Vos guides et vos signalements sont supprimés avec votre compte ; pour supprimer un guide plus tôt, utilisez « Supprimer » ou écrivez à staff@originsmeta.com.",
  },
};

/** Le etichette del modulo di scrittura (client), nella sola lingua della pagina. */
export type GuideEditorLabels = CommunityGuideLabels["editor"] & { errors: CommunityGuideLabels["errors"] };

export function guideEditorLabels(locale: Locale): GuideEditorLabels {
  const L = communityGuideLabels[locale];
  return { ...L.editor, errors: L.errors };
}
