import type { Locale } from "./i18n";
import type { CommentErrorCode } from "./community/comments";

/**
 * Etichette dei commenti sui mazzi della community (02/10/2026): sezione "Commenti" della scheda del mazzo
 * (src/components/comments/DeckComments.tsx) e paragrafo della privacy (#deck-comments). `en` è il tipo di riferimento;
 * il file importa solo tipi. Spagnolo neutro col tú (docs/spagnolo.md). Chi ha pubblicato il mazzo non si chiama mai
 * "Autore" (è un ruolo): "Ha pubblicato il mazzo / Published the deck / Publicó el mazo". Segnaposto: {n}, {max}.
 */

const en = {
  title: "Comments",
  countOne: "1 comment",
  countMany: "{n} comments",
  intro: "Questions, matchups, a card you would swap: write to whoever published the deck and to the other players. Keep it kind: the staff hides off-topic or offensive comments.",
  /** link sotto il voto, verso la sezione */
  jump: "Comment",
  label: "Your comment",
  placeholder: "Write a comment…",
  replyLabel: "Your reply",
  replyPlaceholder: "Write a reply…",
  /** {max} = COMMENT_MAX */
  hint: "Plain text, up to {max} characters.",
  send: "Publish",
  sending: "Publishing…",
  reply: "Reply",
  cancel: "Cancel",
  edit: "Edit",
  save: "Save",
  saving: "Saving…",
  delete: "Delete",
  confirmDelete: "Delete this comment? It can't be undone.",
  report: "Report",
  reportLabel: "Why are you reporting it? (optional)",
  reportSend: "Send report",
  reportDone: "Thanks: the staff will check it.",
  hide: "Hide (staff)",
  unhide: "Show again (staff)",
  hiddenNote: "Hidden by the staff: only whoever wrote it and the staff can see it.",
  deleted: "Comment deleted",
  edited: "edited",
  deckOwner: "Published the deck",
  /** quando il profilo di chi ha scritto non si legge */
  someone: "Account deleted",
  empty: "No comments yet: be the first to write one.",
  loginToComment: "Log in to comment",
  loadMore: "Show more comments",
  loading: "Loading comments…",
  unavailable: "Comments aren't available right now. Try again in a few minutes.",
  utcLabel: "UTC",
  privacyLink: "Privacy",
  errors: {
    notLoggedIn: "Log in to comment.",
    empty: "Write something first.",
    tooLong: "Too long: at most {max} characters.",
    tooFast: "Wait a few seconds between two comments.",
    rate: "You've written a lot of comments: try again later.",
    notFound: "This comment or this deck is no longer online.",
    badParent: "You can't reply to this comment anymore.",
    forbidden: "You can't do this.",
    hidden: "The staff has hidden this comment: it can't be edited.",
    ownComment: "You can't report your own comment.",
    duplicate: "You've already reported this comment.",
    reportRate: "You've sent a lot of reports today: try again tomorrow.",
    reasonTooLong: "The reason is too long: at most 300 characters.",
    unavailable: "Comments aren't available right now. Try again in a few minutes.",
    db: "Something went wrong: try again.",
  } satisfies Record<CommentErrorCode, string>,
  /** paragrafo della privacy (#deck-comments) */
  privacy:
    "Comments on decks: with an account you can comment on the decks published by the community and reply to comments. We store on Supabase (servers in Ireland, EU) the text, the deck, who wrote it and when (and when it was last edited). A comment is public, with your name and profile picture, until you delete it. Whoever published the deck and whoever receives a reply get a notification on the site. To prevent abuse we count each account's recent comments (10 seconds between two comments, at most 20 per hour and 100 per day). The staff can hide or delete comments. Reports (who reports, the comment, the optional reason and when) are read only by the staff; at the first report of a comment our private channel on Discord (Discord Inc., United States) receives the beginning of the comment, the reason, the username of who wrote it and of who reported it. You can delete your comments whenever you want, and comments and reports are deleted with your account.",
};

export type CommentLabels = typeof en;

export const commentLabels: Record<Locale, CommentLabels> = {
  en,
  it: {
    title: "Commenti",
    countOne: "1 commento",
    countMany: "{n} commenti",
    intro: "Domande, matchup, una carta che cambieresti: scrivi a chi ha pubblicato il mazzo e agli altri giocatori. Con gentilezza: lo staff nasconde i commenti fuori tema od offensivi.",
    jump: "Commenta",
    label: "Il tuo commento",
    placeholder: "Scrivi un commento…",
    replyLabel: "La tua risposta",
    replyPlaceholder: "Scrivi una risposta…",
    hint: "Testo semplice, fino a {max} caratteri.",
    send: "Pubblica",
    sending: "Un momento…",
    reply: "Rispondi",
    cancel: "Annulla",
    edit: "Modifica",
    save: "Salva",
    saving: "Un momento…",
    delete: "Elimina",
    confirmDelete: "Eliminare questo commento? Non si torna indietro.",
    report: "Segnala",
    reportLabel: "Perché lo segnali? (facoltativo)",
    reportSend: "Invia la segnalazione",
    reportDone: "Grazie: lo staff lo controllerà.",
    hide: "Nascondi (staff)",
    unhide: "Mostra di nuovo (staff)",
    hiddenNote: "Nascosto dallo staff: lo vedono solo chi l'ha scritto e lo staff.",
    deleted: "Commento eliminato",
    edited: "modificato",
    deckOwner: "Ha pubblicato il mazzo",
    someone: "Account cancellato",
    empty: "Ancora nessun commento: scrivi tu il primo.",
    loginToComment: "Accedi per commentare",
    loadMore: "Mostra altri commenti",
    loading: "Carico i commenti…",
    unavailable: "I commenti non sono disponibili in questo momento. Riprova fra qualche minuto.",
    utcLabel: "UTC",
    privacyLink: "Privacy",
    errors: {
      notLoggedIn: "Accedi per commentare.",
      empty: "Scrivi prima qualcosa.",
      tooLong: "Troppo lungo: al massimo {max} caratteri.",
      tooFast: "Aspetta qualche secondo fra due commenti.",
      rate: "Hai scritto molti commenti: riprova più tardi.",
      notFound: "Questo commento o questo mazzo non è più online.",
      badParent: "A questo commento non si può più rispondere.",
      forbidden: "Non puoi farlo.",
      hidden: "Lo staff ha nascosto questo commento: non si può modificare.",
      ownComment: "Non puoi segnalare un tuo commento.",
      duplicate: "Hai già segnalato questo commento.",
      reportRate: "Oggi hai mandato molte segnalazioni: riprova domani.",
      reasonTooLong: "Il motivo è troppo lungo: al massimo 300 caratteri.",
      unavailable: "I commenti non sono disponibili in questo momento. Riprova fra qualche minuto.",
      db: "Qualcosa è andato storto: riprova.",
    },
    privacy:
      "Commenti ai mazzi: con un account puoi commentare i mazzi pubblicati dalla community e rispondere ai commenti. Su Supabase (server in Irlanda, UE) salviamo il testo, il mazzo, chi l'ha scritto e quando (e quando è stato modificato l'ultima volta). Un commento è pubblico, con il tuo nome e la tua foto profilo, finché non lo cancelli. Chi ha pubblicato il mazzo e chi riceve una risposta ricevono una notifica sul sito. Per evitare abusi contiamo i commenti recenti di ogni account (10 secondi fra due commenti, al massimo 20 l'ora e 100 al giorno). Lo staff può nascondere o cancellare i commenti. Le segnalazioni (chi segnala, il commento, il motivo facoltativo e quando) le legge solo lo staff; alla prima segnalazione di un commento il nostro canale privato su Discord (Discord Inc., Stati Uniti) riceve l'inizio del commento, il motivo, il nome utente di chi l'ha scritto e di chi l'ha segnalato. Puoi cancellare i tuoi commenti quando vuoi, e con l'account si cancellano commenti e segnalazioni.",
  },
  es: {
    title: "Comentarios",
    countOne: "1 comentario",
    countMany: "{n} comentarios",
    intro: "Preguntas, matchups, una carta que cambiarías: escribe a quien publicó el mazo y a los demás jugadores. Con amabilidad: el staff oculta los comentarios fuera de tema u ofensivos.",
    jump: "Comentar",
    label: "Tu comentario",
    placeholder: "Escribe un comentario…",
    replyLabel: "Tu respuesta",
    replyPlaceholder: "Escribe una respuesta…",
    hint: "Texto sin formato, hasta {max} caracteres.",
    send: "Publicar",
    sending: "Un momento…",
    reply: "Responder",
    cancel: "Cancelar",
    edit: "Editar",
    save: "Guardar",
    saving: "Un momento…",
    delete: "Eliminar",
    confirmDelete: "¿Eliminar este comentario? No se puede deshacer.",
    report: "Reportar",
    reportLabel: "¿Por qué lo reportas? (opcional)",
    reportSend: "Enviar el reporte",
    reportDone: "Gracias: el staff lo revisará.",
    hide: "Ocultar (staff)",
    unhide: "Mostrar de nuevo (staff)",
    hiddenNote: "Oculto por el staff: solo lo ven quien lo escribió y el staff.",
    deleted: "Comentario eliminado",
    edited: "editado",
    deckOwner: "Publicó el mazo",
    someone: "Cuenta eliminada",
    empty: "Todavía no hay comentarios: escribe tú el primero.",
    loginToComment: "Inicia sesión para comentar",
    loadMore: "Mostrar más comentarios",
    loading: "Cargando los comentarios…",
    unavailable: "Los comentarios no están disponibles en este momento. Inténtalo de nuevo en unos minutos.",
    utcLabel: "UTC",
    privacyLink: "Privacidad",
    errors: {
      notLoggedIn: "Inicia sesión para comentar.",
      empty: "Escribe algo primero.",
      tooLong: "Demasiado largo: como máximo {max} caracteres.",
      tooFast: "Espera unos segundos entre dos comentarios.",
      rate: "Has escrito muchos comentarios: inténtalo de nuevo más tarde.",
      notFound: "Este comentario o este mazo ya no está en línea.",
      badParent: "Ya no se puede responder a este comentario.",
      forbidden: "No puedes hacerlo.",
      hidden: "El staff ocultó este comentario: no se puede editar.",
      ownComment: "No puedes reportar tu propio comentario.",
      duplicate: "Ya reportaste este comentario.",
      reportRate: "Hoy enviaste muchos reportes: inténtalo de nuevo mañana.",
      reasonTooLong: "El motivo es demasiado largo: como máximo 300 caracteres.",
      unavailable: "Los comentarios no están disponibles en este momento. Inténtalo de nuevo en unos minutos.",
      db: "Algo salió mal: vuelve a intentarlo.",
    },
    privacy:
      "Comentarios en los mazos: con una cuenta puedes comentar los mazos publicados por la comunidad y responder a los comentarios. En Supabase (servidores en Irlanda, UE) guardamos el texto, el mazo, quién lo escribió y cuándo (y cuándo se editó por última vez). Un comentario es público, con tu nombre y tu foto de perfil, hasta que lo eliminas. Quien publicó el mazo y quien recibe una respuesta reciben una notificación en el sitio. Para evitar abusos contamos los comentarios recientes de cada cuenta (10 segundos entre dos comentarios, como máximo 20 por hora y 100 al día). El staff puede ocultar o eliminar comentarios. Los reportes (quién reporta, el comentario, el motivo opcional y cuándo) solo los lee el staff; con el primer reporte de un comentario nuestro canal privado en Discord (Discord Inc., Estados Unidos) recibe el comienzo del comentario, el motivo, el nombre de usuario de quien lo escribió y de quien lo reportó. Puedes eliminar tus comentarios cuando quieras, y con la cuenta se eliminan comentarios y reportes.",
  },
};

/** Sostituisce i segnaposto {nome} (senza i `$` speciali di `replace`). */
export function fillComment(text: string, values: Record<string, string | number>): string {
  return text.replace(/\{(\w+)\}/g, (m, k: string) => (Object.hasOwn(values, k) ? String(values[k]) : m));
}
