import type { Locale } from "./i18n";
import type { DraftFormat } from "./draft/engine";
import type { Grade } from "./draft/bot";
import type { Pkg } from "./draft/ratings";

/**
 * Testi della pagina /draft (02/10/2026, richiesta di Pierluigi: "facciamo un draft da zero MIGLIORE del loro" e
 * "abbiamo un cervello di gioco, usiamolo per fare un bot incazzato nero fortissimo"). Un modulo solo nelle tre lingue,
 * l'inglese è il tipo di riferimento; spagnolo neutro col tú (docs/spagnolo.md), parole del gioco col glossario
 * ufficiale (docs/testi-di-gioco.md): Leggendaria / Legendaria, Alla rivelazione / Al revelar, Alla morte / Al morir.
 *
 * Il voto del bot è un'opinione del bot e le pagine lo dicono: niente "il mazzo migliore", niente win rate.
 * Segnaposto tra graffe ({n}, {total}, {card}…), riempiti con `fill` di tournament/types.ts.
 */
const en = {
  meta: {
    /** titolo della SERP con "Origins TCG" dentro, entro 60 caratteri (test) */
    title: "Origins TCG Draft: build a deck against the Brain",
    description: "Free Origins TCG draft in three formats against the Brain, our bot: pick your cards, build 1 Legendary + 12 and copy the game code. No sign-up.",
    breadcrumb: "Draft",
  },
  kicker: "Deck builder",
  h1: "Origins TCG Draft",
  bot: "the Brain",
  botName: "The Brain",
  setup: {
    chooseFormat: "Choose the format",
    opponent: "Opponent: the Brain, our bot. It only knows what a player in its seat would know.",
    start: "Start the draft",
    shared: "Same draft as the link you received: same cards, same order.",
    resume: "Resume your draft",
    resumeHint: "You have a draft in progress in this browser.",
    discard: "Start a new one",
  },
  formats: {
    exchange: {
      name: "Exchange",
      tagline: "Keep one card, give one to your opponent, the third is burned.",
      rules: [
        "Legendary: pick 1 of 3, the other two are burned.",
        "10 rounds: you see 3 cards. Keep one, give one to your opponent, the third is burned.",
        "Your pool: the 10 you kept and the 10 your opponent gave you. You play 12.",
      ],
    },
    triple: {
      name: "Triple",
      tagline: "Three shared cards: one picks, then the other, the third is burned.",
      rules: [
        "Legendaries: 4 on the table, picked in snake order (A, B, B, A). You keep both and choose one when building.",
        "16 rounds of 3 shared cards: one picks, then the other, the third is burned. The first pick alternates.",
        "Everything is on the table: you see every card your opponent takes. Pool of 16, you play 12.",
      ],
    },
    packs: {
      name: "Packs",
      tagline: "Packs of 6 that you pass back and forth, like a paper TCG.",
      rules: [
        "Legendaries: 4 on the table, picked in snake order, as in Triple.",
        "3 rounds of packs: 1 epic, 2 rares, 3 commons each. You both pick one card from the pack in front of you, then swap packs until they are empty.",
        "You don't see your opponent's picks, only what's left in the packs. Pool of 18, you play 12.",
      ],
    },
  } satisfies Record<DraftFormat, { name: string; tagline: string; rules: string[] }>,
  play: {
    legendaryPhase: "Legendary",
    /** {n} {total} */
    round: "Round {n} of {total}",
    /** {n} {total} */
    pack: "Pack {n} of {total}",
    build: "Build your deck",
    pickLegendary: "Pick your Legendary",
    pick: "Pick a card",
    pickFromPack: "Pick a card from the pack",
    keepGive: "Keep one card and give one to the Brain",
    keep: "Keep",
    give: "Give",
    kept: "Kept",
    given: "Given",
    burned: "Burned",
    confirm: "Confirm",
    waitingBot: "The Brain is thinking…",
    /** {card} */
    botPicked: "The Brain took {card}",
    /** {card} */
    botGave: "The Brain gave you {card}",
    botPickedHidden: "The Brain took a card from its pack",
    /** {card} */
    burnedCard: "{card} is burned",
    yourCards: "Your cards",
    yourLegendaries: "Your Legendaries",
    received: "from the Brain",
    curve: "Mana curve",
    botCards: "The Brain's cards",
    /** {n} */
    botHidden: "{n} cards taken, hidden until the end",
    youGave: "You gave it",
    empty: "Nothing yet",
    lastMove: "Last move",
    restart: "Restart",
    restartConfirm: "Leave this draft and start over?",
    yes: "Yes",
    no: "No",
  },
  buildStep: {
    title: "Build your deck: 1 Legendary and 12 cards",
    hint: "Each card counts twice in the game: 1 + 12 × 2 = 25.",
    /** {n} */
    count: "{n}/12",
    auto: "Build it for me",
    autoHint: "The Brain picks the best 12 for you. You can still change them.",
    clear: "Clear",
    confirm: "Confirm deck",
    chooseLegendary: "Choose your Legendary",
    full: "12 cards already chosen: remove one first.",
  },
  result: {
    title: "Draft complete",
    yourDeck: "Your deck",
    botDeck: "The Brain's deck",
    verdict: "The Brain's verdict",
    verdictNote: "The bot's opinion, from curve, removal and synergies. The real match is played in the game.",
    /** {n} */
    early: "Cards that cost 1–2: {n}",
    /** {n} */
    removal: "Removal: {n}",
    /** {n} */
    barrier: "Barrier damage: {n}",
    /** {n} */
    draw: "Card draw: {n}",
    packages: "Plan",
    noPackage: "no clear package",
    copyGame: "Copy game code",
    copied: "Copied!",
    gameMissing: "Game code not available for this deck",
    openBuilder: "Open in the deck builder",
    replay: "Same draft again",
    newDraft: "New draft",
    challenge: "Challenge a friend on the same draft",
    challengeCopied: "Link copied: send it to a friend",
    challengeHint: "Same cards in the same order against the Brain: compare your verdicts.",
    deckName: "Draft",
  },
  grades: {
    S: "Outstanding",
    A: "Very strong",
    B: "Solid",
    C: "Playable",
    D: "Weak",
  } satisfies Record<Grade, string>,
  packages: {
    discard: "discard",
    spell: "spells",
    heal: "healing",
    move: "Move",
    reveal: "On Reveal",
    death: "On Death",
    evil: "Evil characters",
    good: "Good characters",
    wide: "many characters",
    ally: "allies",
    power: "big bodies",
  } satisfies Record<Pkg, string>,
  notes: {
    intro:
      "A draft is a way to build a deck from cards you don't choose in advance: you and your opponent split them pick by pick, and each of you builds the best deck you can with what you got. OriginsMeta's draft is free, needs no account and ends with a real Origins TCG deck, 1 Legendary and 12 cards, that you can copy into the game with its code or open in the deck builder.",
    formatsTitle: "The three formats",
    botTitle: "How the Brain plays",
    bot: [
      "It values every card with our game notes: what it does, what it costs, which packages it belongs to (discard, spells, healing, Move, On Reveal, On Death, Good and Evil characters).",
      "As the draft goes on it looks more and more at your deck's needs: cards that cost 2 for the first round, removal, barrier damage, card draw.",
      "When you pick right after it, it takes away the card you'd want most if the price is right; in Exchange it gives you the card that helps you least.",
      "It builds its deck by looking for the best 12 together, not one at a time.",
      "It doesn't cheat: it only knows what a player in its seat would know. In Packs it doesn't see your picks, in Exchange only what it gave you.",
    ],
    poolTitle: "The cards",
    /** {count} {patch} */
    pool: "The pool is the {count} playable cards of the Demo 2.0 with today's stats (patch {patch}). Created cards are not in the draft.",
    playTitle: "Playing the deck",
    play: "At the end, copy the game code and paste it into Origins TCG to play the deck, or open it in the deck builder to look at it card by card. The verdict is the bot's opinion: who wins is decided in the game.",
  },
};

export type DraftLabels = typeof en;

const it: DraftLabels = {
  meta: {
    title: "Draft di Origins TCG: costruisci un mazzo contro il Cervello",
    description: "Draft gratuito di Origins TCG in tre formati contro il Cervello, il nostro bot: scegli le carte, fai 1 Leggendaria + 12 e copia il codice del gioco.",
    breadcrumb: "Draft",
  },
  kicker: "Deck builder",
  h1: "Draft di Origins TCG",
  bot: "il Cervello",
  botName: "Il Cervello",
  setup: {
    chooseFormat: "Scegli il formato",
    opponent: "Avversario: il Cervello, il nostro bot. Sa solo quello che saprebbe un giocatore al suo posto.",
    start: "Inizia il draft",
    shared: "Stesso draft del link che hai ricevuto: stesse carte, nello stesso ordine.",
    resume: "Riprendi il draft",
    resumeHint: "Hai un draft in corso in questo browser.",
    discard: "Iniziane uno nuovo",
  },
  formats: {
    exchange: {
      name: "Scambio",
      tagline: "Tieni una carta, regalane una all'avversario, la terza si brucia.",
      rules: [
        "Leggendaria: ne scegli 1 fra 3, le altre due si bruciano.",
        "10 giri: vedi 3 carte. Una la tieni, una la regali all'avversario, la terza si brucia.",
        "Il tuo pool: le 10 che hai tenuto e le 10 che ti ha regalato l'avversario. Ne giochi 12.",
      ],
    },
    triple: {
      name: "Tris",
      tagline: "Tre carte in comune: sceglie uno, poi l'altro, la terza si brucia.",
      rules: [
        "Leggendarie: 4 sul tavolo, scelte a serpentina (A, B, B, A). Le tieni tutte e due e ne scegli una quando costruisci.",
        "16 giri di 3 carte in comune: sceglie uno, poi l'altro, la terza si brucia. Chi sceglie per primo si alterna.",
        "Tutto è sul tavolo: vedi ogni carta che prende l'avversario. Pool di 16, ne giochi 12.",
      ],
    },
    packs: {
      name: "Buste",
      tagline: "Buste da 6 carte che vi passate a vicenda, come nei TCG di carta.",
      rules: [
        "Leggendarie: 4 sul tavolo, scelte a serpentina come nel Tris.",
        "3 giri di buste: 1 epica, 2 rare e 3 comuni ciascuna. Scegliete insieme una carta dalla busta che avete davanti, poi vi scambiate le buste finché sono vuote.",
        "Non vedi le scelte dell'avversario, solo quello che resta nelle buste. Pool di 18, ne giochi 12.",
      ],
    },
  },
  play: {
    legendaryPhase: "Leggendaria",
    round: "Giro {n} di {total}",
    pack: "Busta {n} di {total}",
    build: "Costruisci il mazzo",
    pickLegendary: "Scegli la tua Leggendaria",
    pick: "Scegli una carta",
    pickFromPack: "Scegli una carta dalla busta",
    keepGive: "Tieni una carta e regalane una al Cervello",
    keep: "Tieni",
    give: "Regala",
    kept: "Tenuta",
    given: "Regalata",
    burned: "Bruciata",
    confirm: "Conferma",
    waitingBot: "Il Cervello ci pensa…",
    botPicked: "Il Cervello ha preso {card}",
    botGave: "Il Cervello ti ha regalato {card}",
    botPickedHidden: "Il Cervello ha preso una carta dalla sua busta",
    burnedCard: "{card} si brucia",
    yourCards: "Le tue carte",
    yourLegendaries: "Le tue Leggendarie",
    received: "dal Cervello",
    curve: "Curva di mana",
    botCards: "Le carte del Cervello",
    botHidden: "{n} carte prese, nascoste fino alla fine",
    youGave: "Gli hai regalato",
    empty: "Ancora niente",
    lastMove: "Ultima mossa",
    restart: "Ricomincia",
    restartConfirm: "Lasci questo draft e ricominci?",
    yes: "Sì",
    no: "No",
  },
  buildStep: {
    title: "Costruisci il mazzo: 1 Leggendaria e 12 carte",
    hint: "Nel gioco ogni carta vale due copie: 1 + 12 × 2 = 25.",
    count: "{n}/12",
    auto: "Costruiscilo per me",
    autoHint: "Il Cervello sceglie per te le 12 migliori. Puoi sempre cambiarle.",
    clear: "Svuota",
    confirm: "Conferma il mazzo",
    chooseLegendary: "Scegli la Leggendaria",
    full: "Hai già 12 carte: togline una prima.",
  },
  result: {
    title: "Draft finito",
    yourDeck: "Il tuo mazzo",
    botDeck: "Il mazzo del Cervello",
    verdict: "Il giudizio del Cervello",
    verdictNote: "È l'opinione del bot, su curva, rimozioni e sinergie. La partita vera si gioca nel gioco.",
    early: "Carte da 1–2 mana: {n}",
    removal: "Rimozioni: {n}",
    barrier: "Danno alla barriera: {n}",
    draw: "Pescate: {n}",
    packages: "Piano",
    noPackage: "nessun pacchetto chiaro",
    copyGame: "Copia codice del gioco",
    copied: "Copiato!",
    gameMissing: "Codice del gioco non disponibile per questo mazzo",
    openBuilder: "Apri nel deck builder",
    replay: "Rigioca lo stesso draft",
    newDraft: "Nuovo draft",
    challenge: "Sfida un amico sullo stesso draft",
    challengeCopied: "Link copiato: mandalo a un amico",
    challengeHint: "Stesse carte nello stesso ordine contro il Cervello: confrontate i giudizi.",
    deckName: "Draft",
  },
  grades: {
    S: "Eccezionale",
    A: "Molto forte",
    B: "Solido",
    C: "Giocabile",
    D: "Debole",
  },
  packages: {
    discard: "scarti",
    spell: "magie",
    heal: "cure",
    move: "Muovere",
    reveal: "Alla rivelazione",
    death: "Alla morte",
    evil: "personaggi Malvagi",
    good: "personaggi Buoni",
    wide: "tanti personaggi",
    ally: "alleati",
    power: "corpi grossi",
  },
  notes: {
    intro:
      "Un draft è un modo di costruire un mazzo con carte che non scegli in anticipo: tu e l'avversario ve le dividete una scelta alla volta, e ognuno costruisce il mazzo migliore con quello che ha preso. Il draft di OriginsMeta è gratuito, non chiede l'account e finisce con un mazzo vero di Origins TCG, 1 Leggendaria e 12 carte, da copiare nel gioco con il suo codice o da aprire nel deck builder.",
    formatsTitle: "I tre formati",
    botTitle: "Come gioca il Cervello",
    bot: [
      "Valuta ogni carta con i nostri appunti di gioco: che cosa fa, quanto costa, a quali pacchetti appartiene (scarti, magie, cure, Muovere, Alla rivelazione, Alla morte, personaggi Buoni e Malvagi).",
      "Più il draft va avanti, più guarda i bisogni del mazzo: carte da 2 per il primo round, rimozioni, danno alla barriera, pescate.",
      "Quando scegli subito dopo di lui, ti toglie la carta che vorresti di più se il prezzo è giusto; nello Scambio ti regala la carta che ti serve meno.",
      "Costruisce il suo mazzo cercando le 12 migliori insieme, non una alla volta.",
      "Non bara: sa solo quello che saprebbe un giocatore al suo posto. Nelle Buste non vede le tue scelte, nello Scambio solo quello che ti ha regalato.",
    ],
    poolTitle: "Le carte",
    pool: "Il pool sono le {count} carte giocabili della Demo 2.0 con le statistiche di oggi (patch {patch}). Le carte generate non entrano nel draft.",
    playTitle: "Giocare il mazzo",
    play: "Alla fine copia il codice del gioco e incollalo in Origins TCG per giocare il mazzo, oppure aprilo nel deck builder per guardarlo carta per carta. Il giudizio è un'opinione del bot: chi vince lo decide la partita.",
  },
};

const es: DraftLabels = {
  meta: {
    title: "Draft de Origins TCG: arma un mazo contra el Cerebro",
    description: "Draft gratis de Origins TCG en tres formatos contra el Cerebro, nuestro bot: elige tus cartas, arma 1 Legendaria + 12 y copia el código del juego.",
    breadcrumb: "Draft",
  },
  kicker: "Deck builder",
  h1: "Draft de Origins TCG",
  bot: "el Cerebro",
  botName: "El Cerebro",
  setup: {
    chooseFormat: "Elige el formato",
    opponent: "Rival: el Cerebro, nuestro bot. Solo sabe lo que sabría un jugador en su lugar.",
    start: "Empezar el draft",
    shared: "El mismo draft del enlace que recibiste: mismas cartas, en el mismo orden.",
    resume: "Retomar el draft",
    resumeHint: "Tienes un draft en curso en este navegador.",
    discard: "Empezar uno nuevo",
  },
  formats: {
    exchange: {
      name: "Intercambio",
      tagline: "Te quedas una carta, le regalas otra a tu rival y la tercera se quema.",
      rules: [
        "Legendaria: eliges 1 de 3, las otras dos se queman.",
        "10 rondas: ves 3 cartas. Te quedas una, le regalas otra a tu rival y la tercera se quema.",
        "Tu pool: las 10 que te quedaste y las 10 que te regaló tu rival. Juegas 12.",
      ],
    },
    triple: {
      name: "Trío",
      tagline: "Tres cartas en común: elige uno, luego el otro, la tercera se quema.",
      rules: [
        "Legendarias: 4 sobre la mesa, elegidas en serpiente (A, B, B, A). Te quedas las dos y eliges una al armar el mazo.",
        "16 rondas de 3 cartas en común: elige uno, luego el otro, la tercera se quema. Quien elige primero se alterna.",
        "Todo está sobre la mesa: ves cada carta que toma tu rival. Pool de 16, juegas 12.",
      ],
    },
    packs: {
      name: "Sobres",
      tagline: "Sobres de 6 cartas que se pasan de uno a otro, como en un TCG de papel.",
      rules: [
        "Legendarias: 4 sobre la mesa, elegidas en serpiente como en Trío.",
        "3 rondas de sobres: 1 épica, 2 raras y 3 comunes cada uno. Los dos eligen a la vez una carta del sobre que tienen delante y luego se cambian los sobres hasta vaciarlos.",
        "No ves lo que elige tu rival, solo lo que queda en los sobres. Pool de 18, juegas 12.",
      ],
    },
  },
  play: {
    legendaryPhase: "Legendaria",
    round: "Ronda {n} de {total}",
    pack: "Sobre {n} de {total}",
    build: "Arma tu mazo",
    pickLegendary: "Elige tu Legendaria",
    pick: "Elige una carta",
    pickFromPack: "Elige una carta del sobre",
    keepGive: "Quédate una carta y regálale otra al Cerebro",
    keep: "Quedármela",
    give: "Regalar",
    kept: "Te la quedas",
    given: "Regalada",
    burned: "Quemada",
    confirm: "Confirmar",
    waitingBot: "El Cerebro está pensando…",
    botPicked: "El Cerebro tomó {card}",
    botGave: "El Cerebro te regaló {card}",
    botPickedHidden: "El Cerebro tomó una carta de su sobre",
    burnedCard: "{card} se quema",
    yourCards: "Tus cartas",
    yourLegendaries: "Tus Legendarias",
    received: "del Cerebro",
    curve: "Curva de maná",
    botCards: "Las cartas del Cerebro",
    botHidden: "{n} cartas tomadas, ocultas hasta el final",
    youGave: "Le regalaste",
    empty: "Nada todavía",
    lastMove: "Última jugada",
    restart: "Volver a empezar",
    restartConfirm: "¿Dejas este draft y empiezas de nuevo?",
    yes: "Sí",
    no: "No",
  },
  buildStep: {
    title: "Arma tu mazo: 1 Legendaria y 12 cartas",
    hint: "En el juego cada carta cuenta dos veces: 1 + 12 × 2 = 25.",
    count: "{n}/12",
    auto: "Ármalo por mí",
    autoHint: "El Cerebro elige para ti las 12 mejores. Puedes cambiarlas cuando quieras.",
    clear: "Vaciar",
    confirm: "Confirmar el mazo",
    chooseLegendary: "Elige la Legendaria",
    full: "Ya tienes 12 cartas: quita una primero.",
  },
  result: {
    title: "Draft terminado",
    yourDeck: "Tu mazo",
    botDeck: "El mazo del Cerebro",
    verdict: "El veredicto del Cerebro",
    verdictNote: "Es la opinión del bot, según curva, eliminaciones y sinergias. La partida de verdad se juega en el juego.",
    early: "Cartas de 1–2 de maná: {n}",
    removal: "Eliminaciones: {n}",
    barrier: "Daño a la barrera: {n}",
    draw: "Robo de cartas: {n}",
    packages: "Plan",
    noPackage: "ningún paquete claro",
    copyGame: "Copiar código del juego",
    copied: "¡Copiado!",
    gameMissing: "Código del juego no disponible para este mazo",
    openBuilder: "Abrir en el deck builder",
    replay: "Repetir el mismo draft",
    newDraft: "Nuevo draft",
    challenge: "Reta a un amigo en el mismo draft",
    challengeCopied: "Enlace copiado: envíaselo a un amigo",
    challengeHint: "Las mismas cartas en el mismo orden contra el Cerebro: comparen sus veredictos.",
    deckName: "Draft",
  },
  grades: {
    S: "Excepcional",
    A: "Muy fuerte",
    B: "Sólido",
    C: "Jugable",
    D: "Débil",
  },
  packages: {
    discard: "descartes",
    spell: "hechizos",
    heal: "curación",
    move: "Mover",
    reveal: "Al revelar",
    death: "Al morir",
    evil: "personajes Malvados",
    good: "personajes Buenos",
    wide: "muchos personajes",
    ally: "aliados",
    power: "personajes grandes",
  },
  notes: {
    intro:
      "Un draft es una forma de armar un mazo con cartas que no eliges de antemano: tú y tu rival se las reparten una elección tras otra, y cada uno arma el mejor mazo posible con lo que consiguió. El draft de OriginsMeta es gratis, no pide cuenta y termina con un mazo real de Origins TCG, 1 Legendaria y 12 cartas, que puedes copiar en el juego con su código o abrir en el deck builder.",
    formatsTitle: "Los tres formatos",
    botTitle: "Cómo juega el Cerebro",
    bot: [
      "Valora cada carta con nuestras notas de juego: qué hace, cuánto cuesta, a qué paquetes pertenece (descartes, hechizos, curación, Mover, Al revelar, Al morir, personajes Buenos y Malvados).",
      "A medida que avanza el draft mira cada vez más lo que necesita el mazo: cartas de 2 para la primera ronda, eliminaciones, daño a la barrera, robo de cartas.",
      "Cuando eliges justo después de él, te quita la carta que más querrías si el precio es justo; en Intercambio te regala la carta que menos te sirve.",
      "Arma su mazo buscando las 12 mejores juntas, no una por una.",
      "No hace trampa: solo sabe lo que sabría un jugador en su lugar. En Sobres no ve tus elecciones, en Intercambio solo lo que te regaló.",
    ],
    poolTitle: "Las cartas",
    pool: "El pool son las {count} cartas jugables de la Demo 2.0 con las estadísticas de hoy (parche {patch}). Las cartas creadas no entran en el draft.",
    playTitle: "Jugar el mazo",
    play: "Al final, copia el código del juego y pégalo en Origins TCG para jugar el mazo, o ábrelo en el deck builder para verlo carta por carta. El veredicto es la opinión del bot: quién gana lo decide la partida.",
  },
};

export const draftLabels: Record<Locale, DraftLabels> = { en, it, es };
